/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Status of an active soundboard node.
 * @export
 * @interface ActiveNodeStatus
 */
export interface ActiveNodeStatus {
    /**
     * 
     * @type {number}
     * @memberof ActiveNodeStatus
     */
    duration: number;
    /**
     * 
     * @type {string}
     * @memberof ActiveNodeStatus
     */
    layerId: string;
    /**
     * 
     * @type {string}
     * @memberof ActiveNodeStatus
     */
    nodeId: string;
    /**
     * 
     * @type {boolean}
     * @memberof ActiveNodeStatus
     */
    playing: boolean;
    /**
     * 
     * @type {number}
     * @memberof ActiveNodeStatus
     */
    progress: number;
    /**
     * 
     * @type {string}
     * @memberof ActiveNodeStatus
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ActiveNodeStatus
     */
    url: string;
    /**
     * 
     * @type {number}
     * @memberof ActiveNodeStatus
     */
    volume: number;
}

/**
 * Check if a given object implements the ActiveNodeStatus interface.
 */
export function instanceOfActiveNodeStatus(value: object): value is ActiveNodeStatus {
    if (!('duration' in value) || value['duration'] === undefined) return false;
    if (!('layerId' in value) || value['layerId'] === undefined) return false;
    if (!('nodeId' in value) || value['nodeId'] === undefined) return false;
    if (!('playing' in value) || value['playing'] === undefined) return false;
    if (!('progress' in value) || value['progress'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('volume' in value) || value['volume'] === undefined) return false;
    return true;
}

export function ActiveNodeStatusFromJSON(json: any): ActiveNodeStatus {
    return ActiveNodeStatusFromJSONTyped(json, false);
}

export function ActiveNodeStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActiveNodeStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'duration': json['duration'],
        'layerId': json['layer_id'],
        'nodeId': json['node_id'],
        'playing': json['playing'],
        'progress': json['progress'],
        'title': json['title'],
        'url': json['url'],
        'volume': json['volume'],
    };
}

export function ActiveNodeStatusToJSON(json: any): ActiveNodeStatus {
    return ActiveNodeStatusToJSONTyped(json, false);
}

export function ActiveNodeStatusToJSONTyped(value?: ActiveNodeStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'duration': value['duration'],
        'layer_id': value['layerId'],
        'node_id': value['nodeId'],
        'playing': value['playing'],
        'progress': value['progress'],
        'title': value['title'],
        'url': value['url'],
        'volume': value['volume'],
    };
}

