/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response after selecting a channel.
 * @export
 * @interface ChannelSelectResponse
 */
export interface ChannelSelectResponse {
    /**
     * 
     * @type {string}
     * @memberof ChannelSelectResponse
     */
    error?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ChannelSelectResponse
     */
    success: boolean;
}

/**
 * Check if a given object implements the ChannelSelectResponse interface.
 */
export function instanceOfChannelSelectResponse(value: object): value is ChannelSelectResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function ChannelSelectResponseFromJSON(json: any): ChannelSelectResponse {
    return ChannelSelectResponseFromJSONTyped(json, false);
}

export function ChannelSelectResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelSelectResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
        'success': json['success'],
    };
}

export function ChannelSelectResponseToJSON(json: any): ChannelSelectResponse {
    return ChannelSelectResponseToJSONTyped(json, false);
}

export function ChannelSelectResponseToJSONTyped(value?: ChannelSelectResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'success': value['success'],
    };
}

