/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChannelResponse } from './ChannelResponse';
import {
    ChannelResponseFromJSON,
    ChannelResponseFromJSONTyped,
    ChannelResponseToJSON,
    ChannelResponseToJSONTyped,
} from './ChannelResponse';

/**
 * List of voice channels.
 * @export
 * @interface ChannelsResponse
 */
export interface ChannelsResponse {
    /**
     * 
     * @type {Array<ChannelResponse>}
     * @memberof ChannelsResponse
     */
    channels: Array<ChannelResponse>;
    /**
     * 
     * @type {string}
     * @memberof ChannelsResponse
     */
    currentChannel: string | null;
}

/**
 * Check if a given object implements the ChannelsResponse interface.
 */
export function instanceOfChannelsResponse(value: object): value is ChannelsResponse {
    if (!('channels' in value) || value['channels'] === undefined) return false;
    if (!('currentChannel' in value) || value['currentChannel'] === undefined) return false;
    return true;
}

export function ChannelsResponseFromJSON(json: any): ChannelsResponse {
    return ChannelsResponseFromJSONTyped(json, false);
}

export function ChannelsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'channels': ((json['channels'] as Array<any>).map(ChannelResponseFromJSON)),
        'currentChannel': json['current_channel'],
    };
}

export function ChannelsResponseToJSON(json: any): ChannelsResponse {
    return ChannelsResponseToJSONTyped(json, false);
}

export function ChannelsResponseToJSONTyped(value?: ChannelsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'channels': ((value['channels'] as Array<any>).map(ChannelResponseToJSON)),
        'current_channel': value['currentChannel'],
    };
}

