/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Voice channel information.
 * @export
 * @interface ChannelResponse
 */
export interface ChannelResponse {
    /**
     * 
     * @type {string}
     * @memberof ChannelResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ChannelResponse
     */
    name: string;
}

/**
 * Check if a given object implements the ChannelResponse interface.
 */
export function instanceOfChannelResponse(value: object): value is ChannelResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ChannelResponseFromJSON(json: any): ChannelResponse {
    return ChannelResponseFromJSONTyped(json, false);
}

export function ChannelResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function ChannelResponseToJSON(json: any): ChannelResponse {
    return ChannelResponseToJSONTyped(json, false);
}

export function ChannelResponseToJSONTyped(value?: ChannelResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

