/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Voice connection status.
 * @export
 * @interface ConnectionResponse
 */
export interface ConnectionResponse {
    /**
     * 
     * @type {number}
     * @memberof ConnectionResponse
     */
    channelId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ConnectionResponse
     */
    error?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ConnectionResponse
     */
    status: string;
}

/**
 * Check if a given object implements the ConnectionResponse interface.
 */
export function instanceOfConnectionResponse(value: object): value is ConnectionResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ConnectionResponseFromJSON(json: any): ConnectionResponse {
    return ConnectionResponseFromJSONTyped(json, false);
}

export function ConnectionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'channelId': json['channel_id'] == null ? undefined : json['channel_id'],
        'error': json['error'] == null ? undefined : json['error'],
        'status': json['status'],
    };
}

export function ConnectionResponseToJSON(json: any): ConnectionResponse {
    return ConnectionResponseToJSONTyped(json, false);
}

export function ConnectionResponseToJSONTyped(value?: ConnectionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'channel_id': value['channelId'],
        'error': value['error'],
        'status': value['status'],
    };
}

