/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request to connect to a voice channel.
 * @export
 * @interface ConnectSoundboardRequest
 */
export interface ConnectSoundboardRequest {
    /**
     * 
     * @type {number}
     * @memberof ConnectSoundboardRequest
     */
    channelId: number;
}

/**
 * Check if a given object implements the ConnectSoundboardRequest interface.
 */
export function instanceOfConnectSoundboardRequest(value: object): value is ConnectSoundboardRequest {
    if (!('channelId' in value) || value['channelId'] === undefined) return false;
    return true;
}

export function ConnectSoundboardRequestFromJSON(json: any): ConnectSoundboardRequest {
    return ConnectSoundboardRequestFromJSONTyped(json, false);
}

export function ConnectSoundboardRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectSoundboardRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'channelId': json['channel_id'],
    };
}

export function ConnectSoundboardRequestToJSON(json: any): ConnectSoundboardRequest {
    return ConnectSoundboardRequestToJSONTyped(json, false);
}

export function ConnectSoundboardRequestToJSONTyped(value?: ConnectSoundboardRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'channel_id': value['channelId'],
    };
}

