/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request to create a preset.
 * @export
 * @interface CreatePresetRequest
 */
export interface CreatePresetRequest {
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof CreatePresetRequest
     */
    edges?: Array<{ [key: string]: any; }>;
    /**
     * 
     * @type {number}
     * @memberof CreatePresetRequest
     */
    guildId: number;
    /**
     * 
     * @type {string}
     * @memberof CreatePresetRequest
     */
    name: string;
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof CreatePresetRequest
     */
    nodes?: Array<{ [key: string]: any; }>;
}

/**
 * Check if a given object implements the CreatePresetRequest interface.
 */
export function instanceOfCreatePresetRequest(value: object): value is CreatePresetRequest {
    if (!('guildId' in value) || value['guildId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreatePresetRequestFromJSON(json: any): CreatePresetRequest {
    return CreatePresetRequestFromJSONTyped(json, false);
}

export function CreatePresetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePresetRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'edges': json['edges'] == null ? undefined : json['edges'],
        'guildId': json['guild_id'],
        'name': json['name'],
        'nodes': json['nodes'] == null ? undefined : json['nodes'],
    };
}

export function CreatePresetRequestToJSON(json: any): CreatePresetRequest {
    return CreatePresetRequestToJSONTyped(json, false);
}

export function CreatePresetRequestToJSONTyped(value?: CreatePresetRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'edges': value['edges'],
        'guild_id': value['guildId'],
        'name': value['name'],
        'nodes': value['nodes'],
    };
}

