/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface GetGuildOutput
 */
export interface GetGuildOutput {
	/**
	 *
	 * @type {string}
	 * @memberof GetGuildOutput
	 */
	icon: string;
	/**
	 *
	 * @type {string}
	 * @memberof GetGuildOutput
	 */
	id: string;
	/**
	 *
	 * @type {string}
	 * @memberof GetGuildOutput
	 */
	name: string;
}

/**
 * Check if a given object implements the GetGuildOutput interface.
 */
export function instanceOfGetGuildOutput(value: object): value is GetGuildOutput {
	if (!('icon' in value) || value['icon'] === undefined) return false;
	if (!('id' in value) || value['id'] === undefined) return false;
	if (!('name' in value) || value['name'] === undefined) return false;
	return true;
}

export function GetGuildOutputFromJSON(json: any): GetGuildOutput {
	return GetGuildOutputFromJSONTyped(json, false);
}

export function GetGuildOutputFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): GetGuildOutput {
	if (json == null) {
		return json;
	}
	return {
		icon: json['icon'],
		id: json['id'],
		name: json['name']
	};
}

export function GetGuildOutputToJSON(json: any): GetGuildOutput {
	return GetGuildOutputToJSONTyped(json, false);
}

export function GetGuildOutputToJSONTyped(
	value?: GetGuildOutput | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		icon: value['icon'],
		id: value['id'],
		name: value['name']
	};
}
