/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GuildResponse } from './GuildResponse';
import {
    GuildResponseFromJSON,
    GuildResponseFromJSONTyped,
    GuildResponseToJSON,
    GuildResponseToJSONTyped,
} from './GuildResponse';

/**
 * Response after selecting a guild.
 * @export
 * @interface GuildSelectResponse
 */
export interface GuildSelectResponse {
    /**
     * 
     * @type {string}
     * @memberof GuildSelectResponse
     */
    error?: string | null;
    /**
     * 
     * @type {GuildResponse}
     * @memberof GuildSelectResponse
     */
    guild?: GuildResponse | null;
    /**
     * 
     * @type {boolean}
     * @memberof GuildSelectResponse
     */
    success: boolean;
}

/**
 * Check if a given object implements the GuildSelectResponse interface.
 */
export function instanceOfGuildSelectResponse(value: object): value is GuildSelectResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function GuildSelectResponseFromJSON(json: any): GuildSelectResponse {
    return GuildSelectResponseFromJSONTyped(json, false);
}

export function GuildSelectResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuildSelectResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
        'guild': json['guild'] == null ? undefined : GuildResponseFromJSON(json['guild']),
        'success': json['success'],
    };
}

export function GuildSelectResponseToJSON(json: any): GuildSelectResponse {
    return GuildSelectResponseToJSONTyped(json, false);
}

export function GuildSelectResponseToJSONTyped(value?: GuildSelectResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'guild': GuildResponseToJSON(value['guild']),
        'success': value['success'],
    };
}

