/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Base request containing only guild_id.
 * @export
 * @interface GuildRequest
 */
export interface GuildRequest {
    /**
     * 
     * @type {string}
     * @memberof GuildRequest
     */
    guildId: string;
}

/**
 * Check if a given object implements the GuildRequest interface.
 */
export function instanceOfGuildRequest(value: object): value is GuildRequest {
    if (!('guildId' in value) || value['guildId'] === undefined) return false;
    return true;
}

export function GuildRequestFromJSON(json: any): GuildRequest {
    return GuildRequestFromJSONTyped(json, false);
}

export function GuildRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuildRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'guildId': json['guild_id'],
    };
}

export function GuildRequestToJSON(json: any): GuildRequest {
    return GuildRequestToJSONTyped(json, false);
}

export function GuildRequestToJSONTyped(value?: GuildRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'guild_id': value['guildId'],
    };
}

