/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Discord guild information.
 * @export
 * @interface GuildResponse
 */
export interface GuildResponse {
    /**
     * 
     * @type {string}
     * @memberof GuildResponse
     */
    icon: string;
    /**
     * 
     * @type {string}
     * @memberof GuildResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GuildResponse
     */
    name: string;
}

/**
 * Check if a given object implements the GuildResponse interface.
 */
export function instanceOfGuildResponse(value: object): value is GuildResponse {
    if (!('icon' in value) || value['icon'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function GuildResponseFromJSON(json: any): GuildResponse {
    return GuildResponseFromJSONTyped(json, false);
}

export function GuildResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuildResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'icon': json['icon'],
        'id': json['id'],
        'name': json['name'],
    };
}

export function GuildResponseToJSON(json: any): GuildResponse {
    return GuildResponseToJSONTyped(json, false);
}

export function GuildResponseToJSONTyped(value?: GuildResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'icon': value['icon'],
        'id': value['id'],
        'name': value['name'],
    };
}

