/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request to remove a background layer.
 * @export
 * @interface LayerRemoveRequest
 */
export interface LayerRemoveRequest {
    /**
     * 
     * @type {string}
     * @memberof LayerRemoveRequest
     */
    guildId: string;
    /**
     * 
     * @type {string}
     * @memberof LayerRemoveRequest
     */
    layerId: string;
}

/**
 * Check if a given object implements the LayerRemoveRequest interface.
 */
export function instanceOfLayerRemoveRequest(value: object): value is LayerRemoveRequest {
    if (!('guildId' in value) || value['guildId'] === undefined) return false;
    if (!('layerId' in value) || value['layerId'] === undefined) return false;
    return true;
}

export function LayerRemoveRequestFromJSON(json: any): LayerRemoveRequest {
    return LayerRemoveRequestFromJSONTyped(json, false);
}

export function LayerRemoveRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LayerRemoveRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'guildId': json['guild_id'],
        'layerId': json['layer_id'],
    };
}

export function LayerRemoveRequestToJSON(json: any): LayerRemoveRequest {
    return LayerRemoveRequestToJSONTyped(json, false);
}

export function LayerRemoveRequestToJSONTyped(value?: LayerRemoveRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'guild_id': value['guildId'],
        'layer_id': value['layerId'],
    };
}

