/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request to set a layer's volume.
 * @export
 * @interface LayerVolumeRequest
 */
export interface LayerVolumeRequest {
    /**
     * 
     * @type {string}
     * @memberof LayerVolumeRequest
     */
    guildId: string;
    /**
     * 
     * @type {string}
     * @memberof LayerVolumeRequest
     */
    layerId: string;
    /**
     * 
     * @type {number}
     * @memberof LayerVolumeRequest
     */
    volume: number;
}

/**
 * Check if a given object implements the LayerVolumeRequest interface.
 */
export function instanceOfLayerVolumeRequest(value: object): value is LayerVolumeRequest {
    if (!('guildId' in value) || value['guildId'] === undefined) return false;
    if (!('layerId' in value) || value['layerId'] === undefined) return false;
    if (!('volume' in value) || value['volume'] === undefined) return false;
    return true;
}

export function LayerVolumeRequestFromJSON(json: any): LayerVolumeRequest {
    return LayerVolumeRequestFromJSONTyped(json, false);
}

export function LayerVolumeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LayerVolumeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'guildId': json['guild_id'],
        'layerId': json['layer_id'],
        'volume': json['volume'],
    };
}

export function LayerVolumeRequestToJSON(json: any): LayerVolumeRequest {
    return LayerVolumeRequestToJSONTyped(json, false);
}

export function LayerVolumeRequestToJSONTyped(value?: LayerVolumeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'guild_id': value['guildId'],
        'layer_id': value['layerId'],
        'volume': value['volume'],
    };
}

