/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const LoopMode = {
	NUMBER_0: 0,
	NUMBER_1: 1,
	NUMBER_2: 2
} as const;
export type LoopMode = (typeof LoopMode)[keyof typeof LoopMode];

export function instanceOfLoopMode(value: any): boolean {
	for (const key in LoopMode) {
		if (Object.prototype.hasOwnProperty.call(LoopMode, key)) {
			if (LoopMode[key as keyof typeof LoopMode] === value) {
				return true;
			}
		}
	}
	return false;
}

export function LoopModeFromJSON(json: any): LoopMode {
	return LoopModeFromJSONTyped(json, false);
}

export function LoopModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoopMode {
	return json as LoopMode;
}

export function LoopModeToJSON(value?: LoopMode | null): any {
	return value as any;
}

export function LoopModeToJSONTyped(value: any, ignoreDiscriminator: boolean): LoopMode {
	return value as LoopMode;
}
