/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request to change loop mode.
 * @export
 * @interface LoopRequest
 */
export interface LoopRequest {
    /**
     * 
     * @type {string}
     * @memberof LoopRequest
     */
    guildId: string;
    /**
     * 
     * @type {string}
     * @memberof LoopRequest
     */
    mode: string;
}

/**
 * Check if a given object implements the LoopRequest interface.
 */
export function instanceOfLoopRequest(value: object): value is LoopRequest {
    if (!('guildId' in value) || value['guildId'] === undefined) return false;
    if (!('mode' in value) || value['mode'] === undefined) return false;
    return true;
}

export function LoopRequestFromJSON(json: any): LoopRequest {
    return LoopRequestFromJSONTyped(json, false);
}

export function LoopRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoopRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'guildId': json['guild_id'],
        'mode': json['mode'],
    };
}

export function LoopRequestToJSON(json: any): LoopRequest {
    return LoopRequestToJSONTyped(json, false);
}

export function LoopRequestToJSONTyped(value?: LoopRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'guild_id': value['guildId'],
        'mode': value['mode'],
    };
}

