/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MetadataResponse
 */
export interface MetadataResponse {
    /**
     * 
     * @type {number}
     * @memberof MetadataResponse
     */
    duration: number;
    /**
     * 
     * @type {string}
     * @memberof MetadataResponse
     */
    error?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MetadataResponse
     */
    thumbnail?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MetadataResponse
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof MetadataResponse
     */
    url: string;
}

/**
 * Check if a given object implements the MetadataResponse interface.
 */
export function instanceOfMetadataResponse(value: object): value is MetadataResponse {
    if (!('duration' in value) || value['duration'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function MetadataResponseFromJSON(json: any): MetadataResponse {
    return MetadataResponseFromJSONTyped(json, false);
}

export function MetadataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetadataResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'duration': json['duration'],
        'error': json['error'] == null ? undefined : json['error'],
        'thumbnail': json['thumbnail'] == null ? undefined : json['thumbnail'],
        'title': json['title'],
        'url': json['url'],
    };
}

export function MetadataResponseToJSON(json: any): MetadataResponse {
    return MetadataResponseToJSONTyped(json, false);
}

export function MetadataResponseToJSONTyped(value?: MetadataResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'duration': value['duration'],
        'error': value['error'],
        'thumbnail': value['thumbnail'],
        'title': value['title'],
        'url': value['url'],
    };
}

