/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request to fetch audio metadata.
 * @export
 * @interface MetadataRequest
 */
export interface MetadataRequest {
    /**
     * 
     * @type {string}
     * @memberof MetadataRequest
     */
    url: string;
}

/**
 * Check if a given object implements the MetadataRequest interface.
 */
export function instanceOfMetadataRequest(value: object): value is MetadataRequest {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function MetadataRequestFromJSON(json: any): MetadataRequest {
    return MetadataRequestFromJSONTyped(json, false);
}

export function MetadataRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetadataRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
    };
}

export function MetadataRequestToJSON(json: any): MetadataRequest {
    return MetadataRequestToJSONTyped(json, false);
}

export function MetadataRequestToJSONTyped(value?: MetadataRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
    };
}

