/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QueueItemResponse } from './QueueItemResponse';
import {
    QueueItemResponseFromJSON,
    QueueItemResponseFromJSONTyped,
    QueueItemResponseToJSON,
    QueueItemResponseToJSONTyped,
} from './QueueItemResponse';
import type { MusicTrackResponse } from './MusicTrackResponse';
import {
    MusicTrackResponseFromJSON,
    MusicTrackResponseFromJSONTyped,
    MusicTrackResponseToJSON,
    MusicTrackResponseToJSONTyped,
} from './MusicTrackResponse';
import type { MusicLayerResponse } from './MusicLayerResponse';
import {
    MusicLayerResponseFromJSON,
    MusicLayerResponseFromJSONTyped,
    MusicLayerResponseToJSON,
    MusicLayerResponseToJSONTyped,
} from './MusicLayerResponse';

/**
 * 
 * @export
 * @interface MusicStatusResponse
 */
export interface MusicStatusResponse {
    /**
     * 
     * @type {MusicTrackResponse}
     * @memberof MusicStatusResponse
     */
    currentMusic: MusicTrackResponse | null;
    /**
     * 
     * @type {boolean}
     * @memberof MusicStatusResponse
     */
    isPaused: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MusicStatusResponse
     */
    isPlaying: boolean;
    /**
     * 
     * @type {Array<MusicLayerResponse>}
     * @memberof MusicStatusResponse
     */
    layers: Array<MusicLayerResponse>;
    /**
     * 
     * @type {string}
     * @memberof MusicStatusResponse
     */
    loopMode: string;
    /**
     * 
     * @type {number}
     * @memberof MusicStatusResponse
     */
    progress: number;
    /**
     * 
     * @type {Array<QueueItemResponse>}
     * @memberof MusicStatusResponse
     */
    queue: Array<QueueItemResponse>;
    /**
     * 
     * @type {number}
     * @memberof MusicStatusResponse
     */
    volume: number;
}

/**
 * Check if a given object implements the MusicStatusResponse interface.
 */
export function instanceOfMusicStatusResponse(value: object): value is MusicStatusResponse {
    if (!('currentMusic' in value) || value['currentMusic'] === undefined) return false;
    if (!('isPaused' in value) || value['isPaused'] === undefined) return false;
    if (!('isPlaying' in value) || value['isPlaying'] === undefined) return false;
    if (!('layers' in value) || value['layers'] === undefined) return false;
    if (!('loopMode' in value) || value['loopMode'] === undefined) return false;
    if (!('progress' in value) || value['progress'] === undefined) return false;
    if (!('queue' in value) || value['queue'] === undefined) return false;
    if (!('volume' in value) || value['volume'] === undefined) return false;
    return true;
}

export function MusicStatusResponseFromJSON(json: any): MusicStatusResponse {
    return MusicStatusResponseFromJSONTyped(json, false);
}

export function MusicStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MusicStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'currentMusic': MusicTrackResponseFromJSON(json['current_music']),
        'isPaused': json['is_paused'],
        'isPlaying': json['is_playing'],
        'layers': ((json['layers'] as Array<any>).map(MusicLayerResponseFromJSON)),
        'loopMode': json['loop_mode'],
        'progress': json['progress'],
        'queue': ((json['queue'] as Array<any>).map(QueueItemResponseFromJSON)),
        'volume': json['volume'],
    };
}

export function MusicStatusResponseToJSON(json: any): MusicStatusResponse {
    return MusicStatusResponseToJSONTyped(json, false);
}

export function MusicStatusResponseToJSONTyped(value?: MusicStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'current_music': MusicTrackResponseToJSON(value['currentMusic']),
        'is_paused': value['isPaused'],
        'is_playing': value['isPlaying'],
        'layers': ((value['layers'] as Array<any>).map(MusicLayerResponseToJSON)),
        'loop_mode': value['loopMode'],
        'progress': value['progress'],
        'queue': ((value['queue'] as Array<any>).map(QueueItemResponseToJSON)),
        'volume': value['volume'],
    };
}

