/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Legacy control request (deprecated).
 * @export
 * @interface MusicControlRequest
 */
export interface MusicControlRequest {
    /**
     * 
     * @type {MusicControlRequestActionEnum}
     * @memberof MusicControlRequest
     */
    action: MusicControlRequestActionEnum;
    /**
     * 
     * @type {string}
     * @memberof MusicControlRequest
     */
    guildId: string;
    /**
     * 
     * @type {string}
     * @memberof MusicControlRequest
     */
    layerId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MusicControlRequest
     */
    mode: string | null;
    /**
     * 
     * @type {number}
     * @memberof MusicControlRequest
     */
    volume?: number | null;
}


/**
 * @export
 */
export const MusicControlRequestActionEnum = {
    Stop: 'stop',
    Skip: 'skip',
    Pause: 'pause',
    Resume: 'resume',
    Loop: 'loop',
    RemoveLayer: 'remove_layer',
    CleanLayers: 'clean_layers',
    SetVolume: 'set_volume',
    SetLayerVolume: 'set_layer_volume'
} as const;
export type MusicControlRequestActionEnum = typeof MusicControlRequestActionEnum[keyof typeof MusicControlRequestActionEnum];


/**
 * Check if a given object implements the MusicControlRequest interface.
 */
export function instanceOfMusicControlRequest(value: object): value is MusicControlRequest {
    if (!('action' in value) || value['action'] === undefined) return false;
    if (!('guildId' in value) || value['guildId'] === undefined) return false;
    if (!('mode' in value) || value['mode'] === undefined) return false;
    return true;
}

export function MusicControlRequestFromJSON(json: any): MusicControlRequest {
    return MusicControlRequestFromJSONTyped(json, false);
}

export function MusicControlRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MusicControlRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'action': json['action'],
        'guildId': json['guild_id'],
        'layerId': json['layer_id'] == null ? undefined : json['layer_id'],
        'mode': json['mode'],
        'volume': json['volume'] == null ? undefined : json['volume'],
    };
}

export function MusicControlRequestToJSON(json: any): MusicControlRequest {
    return MusicControlRequestToJSONTyped(json, false);
}

export function MusicControlRequestToJSONTyped(value?: MusicControlRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': value['action'],
        'guild_id': value['guildId'],
        'layer_id': value['layerId'],
        'mode': value['mode'],
        'volume': value['volume'],
    };
}

