/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response after adding music.
 * @export
 * @interface MusicAddResponse
 */
export interface MusicAddResponse {
    /**
     * 
     * @type {string}
     * @memberof MusicAddResponse
     */
    error?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MusicAddResponse
     */
    status: string;
}

/**
 * Check if a given object implements the MusicAddResponse interface.
 */
export function instanceOfMusicAddResponse(value: object): value is MusicAddResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function MusicAddResponseFromJSON(json: any): MusicAddResponse {
    return MusicAddResponseFromJSONTyped(json, false);
}

export function MusicAddResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MusicAddResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
        'status': json['status'],
    };
}

export function MusicAddResponseToJSON(json: any): MusicAddResponse {
    return MusicAddResponseToJSONTyped(json, false);
}

export function MusicAddResponseToJSONTyped(value?: MusicAddResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'status': value['status'],
    };
}

