/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request to add music to queue or as a layer.
 * @export
 * @interface MusicAddRequest
 */
export interface MusicAddRequest {
    /**
     * 
     * @type {string}
     * @memberof MusicAddRequest
     */
    channelId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MusicAddRequest
     */
    guildId: string;
    /**
     * 
     * @type {string}
     * @memberof MusicAddRequest
     */
    link: string;
    /**
     * 
     * @type {MusicAddRequestTypeEnum}
     * @memberof MusicAddRequest
     */
    type?: MusicAddRequestTypeEnum;
}


/**
 * @export
 */
export const MusicAddRequestTypeEnum = {
    Queue: 'queue',
    Layer: 'layer'
} as const;
export type MusicAddRequestTypeEnum = typeof MusicAddRequestTypeEnum[keyof typeof MusicAddRequestTypeEnum];


/**
 * Check if a given object implements the MusicAddRequest interface.
 */
export function instanceOfMusicAddRequest(value: object): value is MusicAddRequest {
    if (!('guildId' in value) || value['guildId'] === undefined) return false;
    if (!('link' in value) || value['link'] === undefined) return false;
    return true;
}

export function MusicAddRequestFromJSON(json: any): MusicAddRequest {
    return MusicAddRequestFromJSONTyped(json, false);
}

export function MusicAddRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MusicAddRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'channelId': json['channel_id'] == null ? undefined : json['channel_id'],
        'guildId': json['guild_id'],
        'link': json['link'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function MusicAddRequestToJSON(json: any): MusicAddRequest {
    return MusicAddRequestToJSONTyped(json, false);
}

export function MusicAddRequestToJSONTyped(value?: MusicAddRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'channel_id': value['channelId'],
        'guild_id': value['guildId'],
        'link': value['link'],
        'type': value['type'],
    };
}

