/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MusicTrackResponse
 */
export interface MusicTrackResponse {
    /**
     * 
     * @type {number}
     * @memberof MusicTrackResponse
     */
    duration: number;
    /**
     * 
     * @type {string}
     * @memberof MusicTrackResponse
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof MusicTrackResponse
     */
    url: string;
}

/**
 * Check if a given object implements the MusicTrackResponse interface.
 */
export function instanceOfMusicTrackResponse(value: object): value is MusicTrackResponse {
    if (!('duration' in value) || value['duration'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function MusicTrackResponseFromJSON(json: any): MusicTrackResponse {
    return MusicTrackResponseFromJSONTyped(json, false);
}

export function MusicTrackResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MusicTrackResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'duration': json['duration'],
        'title': json['title'],
        'url': json['url'],
    };
}

export function MusicTrackResponseToJSON(json: any): MusicTrackResponse {
    return MusicTrackResponseToJSONTyped(json, false);
}

export function MusicTrackResponseToJSONTyped(value?: MusicTrackResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'duration': value['duration'],
        'title': value['title'],
        'url': value['url'],
    };
}

