/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MusicControlResponse
 */
export interface MusicControlResponse {
    /**
     * 
     * @type {string}
     * @memberof MusicControlResponse
     */
    error?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MusicControlResponse
     */
    status: string;
}

/**
 * Check if a given object implements the MusicControlResponse interface.
 */
export function instanceOfMusicControlResponse(value: object): value is MusicControlResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function MusicControlResponseFromJSON(json: any): MusicControlResponse {
    return MusicControlResponseFromJSONTyped(json, false);
}

export function MusicControlResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MusicControlResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
        'status': json['status'],
    };
}

export function MusicControlResponseToJSON(json: any): MusicControlResponse {
    return MusicControlResponseToJSONTyped(json, false);
}

export function MusicControlResponseToJSONTyped(value?: MusicControlResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'status': value['status'],
    };
}

