/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Background audio layer information.
 * @export
 * @interface MusicLayerResponse
 */
export interface MusicLayerResponse {
    /**
     * 
     * @type {string}
     * @memberof MusicLayerResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof MusicLayerResponse
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof MusicLayerResponse
     */
    url: string;
    /**
     * 
     * @type {number}
     * @memberof MusicLayerResponse
     */
    volume: number;
}

/**
 * Check if a given object implements the MusicLayerResponse interface.
 */
export function instanceOfMusicLayerResponse(value: object): value is MusicLayerResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('volume' in value) || value['volume'] === undefined) return false;
    return true;
}

export function MusicLayerResponseFromJSON(json: any): MusicLayerResponse {
    return MusicLayerResponseFromJSONTyped(json, false);
}

export function MusicLayerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MusicLayerResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'url': json['url'],
        'volume': json['volume'],
    };
}

export function MusicLayerResponseToJSON(json: any): MusicLayerResponse {
    return MusicLayerResponseToJSONTyped(json, false);
}

export function MusicLayerResponseToJSONTyped(value?: MusicLayerResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'url': value['url'],
        'volume': value['volume'],
    };
}

