/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodeLoopRequest
 */
export interface NodeLoopRequest {
    /**
     * 
     * @type {string}
     * @memberof NodeLoopRequest
     */
    guildId: string;
    /**
     * 
     * @type {boolean}
     * @memberof NodeLoopRequest
     */
    loop: boolean;
    /**
     * 
     * @type {string}
     * @memberof NodeLoopRequest
     */
    nodeId: string;
}

/**
 * Check if a given object implements the NodeLoopRequest interface.
 */
export function instanceOfNodeLoopRequest(value: object): value is NodeLoopRequest {
    if (!('guildId' in value) || value['guildId'] === undefined) return false;
    if (!('loop' in value) || value['loop'] === undefined) return false;
    if (!('nodeId' in value) || value['nodeId'] === undefined) return false;
    return true;
}

export function NodeLoopRequestFromJSON(json: any): NodeLoopRequest {
    return NodeLoopRequestFromJSONTyped(json, false);
}

export function NodeLoopRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeLoopRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'guildId': json['guild_id'],
        'loop': json['loop'],
        'nodeId': json['node_id'],
    };
}

export function NodeLoopRequestToJSON(json: any): NodeLoopRequest {
    return NodeLoopRequestToJSONTyped(json, false);
}

export function NodeLoopRequestToJSONTyped(value?: NodeLoopRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'guild_id': value['guildId'],
        'loop': value['loop'],
        'node_id': value['nodeId'],
    };
}

