/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request to set a node's volume.
 * @export
 * @interface NodeVolumeRequest
 */
export interface NodeVolumeRequest {
    /**
     * 
     * @type {string}
     * @memberof NodeVolumeRequest
     */
    guildId: string;
    /**
     * 
     * @type {string}
     * @memberof NodeVolumeRequest
     */
    nodeId: string;
    /**
     * 
     * @type {number}
     * @memberof NodeVolumeRequest
     */
    volume: number;
}

/**
 * Check if a given object implements the NodeVolumeRequest interface.
 */
export function instanceOfNodeVolumeRequest(value: object): value is NodeVolumeRequest {
    if (!('guildId' in value) || value['guildId'] === undefined) return false;
    if (!('nodeId' in value) || value['nodeId'] === undefined) return false;
    if (!('volume' in value) || value['volume'] === undefined) return false;
    return true;
}

export function NodeVolumeRequestFromJSON(json: any): NodeVolumeRequest {
    return NodeVolumeRequestFromJSONTyped(json, false);
}

export function NodeVolumeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeVolumeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'guildId': json['guild_id'],
        'nodeId': json['node_id'],
        'volume': json['volume'],
    };
}

export function NodeVolumeRequestToJSON(json: any): NodeVolumeRequest {
    return NodeVolumeRequestToJSONTyped(json, false);
}

export function NodeVolumeRequestToJSONTyped(value?: NodeVolumeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'guild_id': value['guildId'],
        'node_id': value['nodeId'],
        'volume': value['volume'],
    };
}

