/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Soundboard preset data.
 * @export
 * @interface PresetResponse
 */
export interface PresetResponse {
    /**
     * 
     * @type {string}
     * @memberof PresetResponse
     */
    createdAt: string;
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof PresetResponse
     */
    edges: Array<{ [key: string]: any; }>;
    /**
     * 
     * @type {number}
     * @memberof PresetResponse
     */
    guildId: number;
    /**
     * 
     * @type {string}
     * @memberof PresetResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PresetResponse
     */
    name: string;
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof PresetResponse
     */
    nodes: Array<{ [key: string]: any; }>;
    /**
     * 
     * @type {string}
     * @memberof PresetResponse
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the PresetResponse interface.
 */
export function instanceOfPresetResponse(value: object): value is PresetResponse {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('edges' in value) || value['edges'] === undefined) return false;
    if (!('guildId' in value) || value['guildId'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('nodes' in value) || value['nodes'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function PresetResponseFromJSON(json: any): PresetResponse {
    return PresetResponseFromJSONTyped(json, false);
}

export function PresetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PresetResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'],
        'edges': json['edges'],
        'guildId': json['guild_id'],
        'id': json['id'],
        'name': json['name'],
        'nodes': json['nodes'],
        'updatedAt': json['updated_at'],
    };
}

export function PresetResponseToJSON(json: any): PresetResponse {
    return PresetResponseToJSONTyped(json, false);
}

export function PresetResponseToJSONTyped(value?: PresetResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'],
        'edges': value['edges'],
        'guild_id': value['guildId'],
        'id': value['id'],
        'name': value['name'],
        'nodes': value['nodes'],
        'updated_at': value['updatedAt'],
    };
}

