/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * List of soundboard presets.
 * @export
 * @interface PresetListResponse
 */
export interface PresetListResponse {
    /**
     * 
     * @type {string}
     * @memberof PresetListResponse
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof PresetListResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PresetListResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PresetListResponse
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the PresetListResponse interface.
 */
export function instanceOfPresetListResponse(value: object): value is PresetListResponse {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function PresetListResponseFromJSON(json: any): PresetListResponse {
    return PresetListResponseFromJSONTyped(json, false);
}

export function PresetListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PresetListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'],
        'id': json['id'],
        'name': json['name'],
        'updatedAt': json['updated_at'],
    };
}

export function PresetListResponseToJSON(json: any): PresetListResponse {
    return PresetListResponseToJSONTyped(json, false);
}

export function PresetListResponseToJSONTyped(value?: PresetListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'],
        'id': value['id'],
        'name': value['name'],
        'updated_at': value['updatedAt'],
    };
}

