/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PresetResponse1
 */
export interface PresetResponse1 {
	/**
	 *
	 * @type {string}
	 * @memberof PresetResponse1
	 */
	createdAt: string;
	/**
	 *
	 * @type {Array<{ [key: string]: any; }>}
	 * @memberof PresetResponse1
	 */
	edges: Array<{ [key: string]: any }>;
	/**
	 *
	 * @type {number}
	 * @memberof PresetResponse1
	 */
	guildId: number;
	/**
	 *
	 * @type {string}
	 * @memberof PresetResponse1
	 */
	id: string;
	/**
	 *
	 * @type {string}
	 * @memberof PresetResponse1
	 */
	name: string;
	/**
	 *
	 * @type {Array<{ [key: string]: any; }>}
	 * @memberof PresetResponse1
	 */
	nodes: Array<{ [key: string]: any }>;
	/**
	 *
	 * @type {string}
	 * @memberof PresetResponse1
	 */
	updatedAt: string;
}

/**
 * Check if a given object implements the PresetResponse1 interface.
 */
export function instanceOfPresetResponse1(value: object): value is PresetResponse1 {
	if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
	if (!('edges' in value) || value['edges'] === undefined) return false;
	if (!('guildId' in value) || value['guildId'] === undefined) return false;
	if (!('id' in value) || value['id'] === undefined) return false;
	if (!('name' in value) || value['name'] === undefined) return false;
	if (!('nodes' in value) || value['nodes'] === undefined) return false;
	if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
	return true;
}

export function PresetResponse1FromJSON(json: any): PresetResponse1 {
	return PresetResponse1FromJSONTyped(json, false);
}

export function PresetResponse1FromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): PresetResponse1 {
	if (json == null) {
		return json;
	}
	return {
		createdAt: json['created_at'],
		edges: json['edges'],
		guildId: json['guild_id'],
		id: json['id'],
		name: json['name'],
		nodes: json['nodes'],
		updatedAt: json['updated_at']
	};
}

export function PresetResponse1ToJSON(json: any): PresetResponse1 {
	return PresetResponse1ToJSONTyped(json, false);
}

export function PresetResponse1ToJSONTyped(
	value?: PresetResponse1 | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		created_at: value['createdAt'],
		edges: value['edges'],
		guild_id: value['guildId'],
		id: value['id'],
		name: value['name'],
		nodes: value['nodes'],
		updated_at: value['updatedAt']
	};
}
