/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QueueItemResponse
 */
export interface QueueItemResponse {
    /**
     * 
     * @type {number}
     * @memberof QueueItemResponse
     */
    duration: number;
    /**
     * 
     * @type {string}
     * @memberof QueueItemResponse
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof QueueItemResponse
     */
    url: string;
}

/**
 * Check if a given object implements the QueueItemResponse interface.
 */
export function instanceOfQueueItemResponse(value: object): value is QueueItemResponse {
    if (!('duration' in value) || value['duration'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function QueueItemResponseFromJSON(json: any): QueueItemResponse {
    return QueueItemResponseFromJSONTyped(json, false);
}

export function QueueItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueueItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'duration': json['duration'],
        'title': json['title'],
        'url': json['url'],
    };
}

export function QueueItemResponseToJSON(json: any): QueueItemResponse {
    return QueueItemResponseToJSONTyped(json, false);
}

export function QueueItemResponseToJSONTyped(value?: QueueItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'duration': value['duration'],
        'title': value['title'],
        'url': value['url'],
    };
}

