/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SelectGuildRequest
 */
export interface SelectGuildRequest {
    /**
     * 
     * @type {string}
     * @memberof SelectGuildRequest
     */
    guildId: string;
}

/**
 * Check if a given object implements the SelectGuildRequest interface.
 */
export function instanceOfSelectGuildRequest(value: object): value is SelectGuildRequest {
    if (!('guildId' in value) || value['guildId'] === undefined) return false;
    return true;
}

export function SelectGuildRequestFromJSON(json: any): SelectGuildRequest {
    return SelectGuildRequestFromJSONTyped(json, false);
}

export function SelectGuildRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SelectGuildRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'guildId': json['guild_id'],
    };
}

export function SelectGuildRequestToJSON(json: any): SelectGuildRequest {
    return SelectGuildRequestToJSONTyped(json, false);
}

export function SelectGuildRequestToJSONTyped(value?: SelectGuildRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'guild_id': value['guildId'],
    };
}

