/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SelectChannelInput
 */
export interface SelectChannelInput {
	/**
	 *
	 * @type {string}
	 * @memberof SelectChannelInput
	 */
	channelId: string;
	/**
	 *
	 * @type {string}
	 * @memberof SelectChannelInput
	 */
	guildId: string;
}

/**
 * Check if a given object implements the SelectChannelInput interface.
 */
export function instanceOfSelectChannelInput(value: object): value is SelectChannelInput {
	if (!('channelId' in value) || value['channelId'] === undefined) return false;
	if (!('guildId' in value) || value['guildId'] === undefined) return false;
	return true;
}

export function SelectChannelInputFromJSON(json: any): SelectChannelInput {
	return SelectChannelInputFromJSONTyped(json, false);
}

export function SelectChannelInputFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): SelectChannelInput {
	if (json == null) {
		return json;
	}
	return {
		channelId: json['channel_id'],
		guildId: json['guild_id']
	};
}

export function SelectChannelInputToJSON(json: any): SelectChannelInput {
	return SelectChannelInputToJSONTyped(json, false);
}

export function SelectChannelInputToJSONTyped(
	value?: SelectChannelInput | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		channel_id: value['channelId'],
		guild_id: value['guildId']
	};
}
