/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request to select a voice channel.
 * @export
 * @interface SelectChannelRequest
 */
export interface SelectChannelRequest {
    /**
     * 
     * @type {string}
     * @memberof SelectChannelRequest
     */
    channelId: string;
    /**
     * 
     * @type {string}
     * @memberof SelectChannelRequest
     */
    guildId: string;
}

/**
 * Check if a given object implements the SelectChannelRequest interface.
 */
export function instanceOfSelectChannelRequest(value: object): value is SelectChannelRequest {
    if (!('channelId' in value) || value['channelId'] === undefined) return false;
    if (!('guildId' in value) || value['guildId'] === undefined) return false;
    return true;
}

export function SelectChannelRequestFromJSON(json: any): SelectChannelRequest {
    return SelectChannelRequestFromJSONTyped(json, false);
}

export function SelectChannelRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SelectChannelRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'channelId': json['channel_id'],
        'guildId': json['guild_id'],
    };
}

export function SelectChannelRequestToJSON(json: any): SelectChannelRequest {
    return SelectChannelRequestToJSONTyped(json, false);
}

export function SelectChannelRequestToJSONTyped(value?: SelectChannelRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'channel_id': value['channelId'],
        'guild_id': value['guildId'],
    };
}

