/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SelectGuildInput
 */
export interface SelectGuildInput {
	/**
	 *
	 * @type {string}
	 * @memberof SelectGuildInput
	 */
	guildId: string;
}

/**
 * Check if a given object implements the SelectGuildInput interface.
 */
export function instanceOfSelectGuildInput(value: object): value is SelectGuildInput {
	if (!('guildId' in value) || value['guildId'] === undefined) return false;
	return true;
}

export function SelectGuildInputFromJSON(json: any): SelectGuildInput {
	return SelectGuildInputFromJSONTyped(json, false);
}

export function SelectGuildInputFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): SelectGuildInput {
	if (json == null) {
		return json;
	}
	return {
		guildId: json['guild_id']
	};
}

export function SelectGuildInputToJSON(json: any): SelectGuildInput {
	return SelectGuildInputToJSONTyped(json, false);
}

export function SelectGuildInputToJSONTyped(
	value?: SelectGuildInput | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		guild_id: value['guildId']
	};
}
