/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServerStatusModel
 */
export interface ServerStatusModel {
    /**
     * 
     * @type {number}
     * @memberof ServerStatusModel
     */
    cpu: number;
    /**
     * 
     * @type {number}
     * @memberof ServerStatusModel
     */
    memoryAvailable: number;
    /**
     * 
     * @type {number}
     * @memberof ServerStatusModel
     */
    memoryFree: number;
    /**
     * 
     * @type {number}
     * @memberof ServerStatusModel
     */
    memoryPercent: number;
    /**
     * 
     * @type {number}
     * @memberof ServerStatusModel
     */
    memoryTotal: number;
    /**
     * 
     * @type {number}
     * @memberof ServerStatusModel
     */
    memoryUsed: number;
}

/**
 * Check if a given object implements the ServerStatusModel interface.
 */
export function instanceOfServerStatusModel(value: object): value is ServerStatusModel {
    if (!('cpu' in value) || value['cpu'] === undefined) return false;
    if (!('memoryAvailable' in value) || value['memoryAvailable'] === undefined) return false;
    if (!('memoryFree' in value) || value['memoryFree'] === undefined) return false;
    if (!('memoryPercent' in value) || value['memoryPercent'] === undefined) return false;
    if (!('memoryTotal' in value) || value['memoryTotal'] === undefined) return false;
    if (!('memoryUsed' in value) || value['memoryUsed'] === undefined) return false;
    return true;
}

export function ServerStatusModelFromJSON(json: any): ServerStatusModel {
    return ServerStatusModelFromJSONTyped(json, false);
}

export function ServerStatusModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerStatusModel {
    if (json == null) {
        return json;
    }
    return {
        
        'cpu': json['cpu'],
        'memoryAvailable': json['memory_available'],
        'memoryFree': json['memory_free'],
        'memoryPercent': json['memory_percent'],
        'memoryTotal': json['memory_total'],
        'memoryUsed': json['memory_used'],
    };
}

export function ServerStatusModelToJSON(json: any): ServerStatusModel {
    return ServerStatusModelToJSONTyped(json, false);
}

export function ServerStatusModelToJSONTyped(value?: ServerStatusModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cpu': value['cpu'],
        'memory_available': value['memoryAvailable'],
        'memory_free': value['memoryFree'],
        'memory_percent': value['memoryPercent'],
        'memory_total': value['memoryTotal'],
        'memory_used': value['memoryUsed'],
    };
}

