/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Soundboard graph state.
 * @export
 * @interface SoundboardGraphResponse2
 */
export interface SoundboardGraphResponse2 {
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof SoundboardGraphResponse2
     */
    edges: Array<{ [key: string]: any; }>;
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof SoundboardGraphResponse2
     */
    nodes: Array<{ [key: string]: any; }>;
}

/**
 * Check if a given object implements the SoundboardGraphResponse2 interface.
 */
export function instanceOfSoundboardGraphResponse2(value: object): value is SoundboardGraphResponse2 {
    if (!('edges' in value) || value['edges'] === undefined) return false;
    if (!('nodes' in value) || value['nodes'] === undefined) return false;
    return true;
}

export function SoundboardGraphResponse2FromJSON(json: any): SoundboardGraphResponse2 {
    return SoundboardGraphResponse2FromJSONTyped(json, false);
}

export function SoundboardGraphResponse2FromJSONTyped(json: any, ignoreDiscriminator: boolean): SoundboardGraphResponse2 {
    if (json == null) {
        return json;
    }
    return {
        
        'edges': json['edges'],
        'nodes': json['nodes'],
    };
}

export function SoundboardGraphResponse2ToJSON(json: any): SoundboardGraphResponse2 {
    return SoundboardGraphResponse2ToJSONTyped(json, false);
}

export function SoundboardGraphResponse2ToJSONTyped(value?: SoundboardGraphResponse2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'edges': value['edges'],
        'nodes': value['nodes'],
    };
}

