/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SoundboardGraphResponse } from './SoundboardGraphResponse';
import {
    SoundboardGraphResponseFromJSON,
    SoundboardGraphResponseFromJSONTyped,
    SoundboardGraphResponseToJSON,
    SoundboardGraphResponseToJSONTyped,
} from './SoundboardGraphResponse';
import type { ActiveNodeStatus } from './ActiveNodeStatus';
import {
    ActiveNodeStatusFromJSON,
    ActiveNodeStatusFromJSONTyped,
    ActiveNodeStatusToJSON,
    ActiveNodeStatusToJSONTyped,
} from './ActiveNodeStatus';

/**
 * 
 * @export
 * @interface SoundboardStatusResponse
 */
export interface SoundboardStatusResponse {
    /**
     * 
     * @type {Array<ActiveNodeStatus>}
     * @memberof SoundboardStatusResponse
     */
    activeNodes: Array<ActiveNodeStatus>;
    /**
     * 
     * @type {number}
     * @memberof SoundboardStatusResponse
     */
    channelId: number | null;
    /**
     * 
     * @type {string}
     * @memberof SoundboardStatusResponse
     */
    channelName: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof SoundboardStatusResponse
     */
    connected: boolean;
    /**
     * 
     * @type {SoundboardGraphResponse}
     * @memberof SoundboardStatusResponse
     */
    graph: SoundboardGraphResponse | null;
}

/**
 * Check if a given object implements the SoundboardStatusResponse interface.
 */
export function instanceOfSoundboardStatusResponse(value: object): value is SoundboardStatusResponse {
    if (!('activeNodes' in value) || value['activeNodes'] === undefined) return false;
    if (!('channelId' in value) || value['channelId'] === undefined) return false;
    if (!('channelName' in value) || value['channelName'] === undefined) return false;
    if (!('connected' in value) || value['connected'] === undefined) return false;
    if (!('graph' in value) || value['graph'] === undefined) return false;
    return true;
}

export function SoundboardStatusResponseFromJSON(json: any): SoundboardStatusResponse {
    return SoundboardStatusResponseFromJSONTyped(json, false);
}

export function SoundboardStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SoundboardStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'activeNodes': ((json['active_nodes'] as Array<any>).map(ActiveNodeStatusFromJSON)),
        'channelId': json['channel_id'],
        'channelName': json['channel_name'],
        'connected': json['connected'],
        'graph': SoundboardGraphResponseFromJSON(json['graph']),
    };
}

export function SoundboardStatusResponseToJSON(json: any): SoundboardStatusResponse {
    return SoundboardStatusResponseToJSONTyped(json, false);
}

export function SoundboardStatusResponseToJSONTyped(value?: SoundboardStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active_nodes': ((value['activeNodes'] as Array<any>).map(ActiveNodeStatusToJSON)),
        'channel_id': value['channelId'],
        'channel_name': value['channelName'],
        'connected': value['connected'],
        'graph': SoundboardGraphResponseToJSON(value['graph']),
    };
}

