/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SoundboardGraphResponse
 */
export interface SoundboardGraphResponse {
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof SoundboardGraphResponse
     */
    edges: Array<{ [key: string]: any; }>;
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof SoundboardGraphResponse
     */
    nodes: Array<{ [key: string]: any; }>;
}

/**
 * Check if a given object implements the SoundboardGraphResponse interface.
 */
export function instanceOfSoundboardGraphResponse(value: object): value is SoundboardGraphResponse {
    if (!('edges' in value) || value['edges'] === undefined) return false;
    if (!('nodes' in value) || value['nodes'] === undefined) return false;
    return true;
}

export function SoundboardGraphResponseFromJSON(json: any): SoundboardGraphResponse {
    return SoundboardGraphResponseFromJSONTyped(json, false);
}

export function SoundboardGraphResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SoundboardGraphResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'edges': json['edges'],
        'nodes': json['nodes'],
    };
}

export function SoundboardGraphResponseToJSON(json: any): SoundboardGraphResponse {
    return SoundboardGraphResponseToJSONTyped(json, false);
}

export function SoundboardGraphResponseToJSONTyped(value?: SoundboardGraphResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'edges': value['edges'],
        'nodes': value['nodes'],
    };
}

