/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SoundboardGraphResponse1
 */
export interface SoundboardGraphResponse1 {
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof SoundboardGraphResponse1
     */
    edges: Array<{ [key: string]: any; }>;
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof SoundboardGraphResponse1
     */
    nodes: Array<{ [key: string]: any; }>;
}

/**
 * Check if a given object implements the SoundboardGraphResponse1 interface.
 */
export function instanceOfSoundboardGraphResponse1(value: object): value is SoundboardGraphResponse1 {
    if (!('edges' in value) || value['edges'] === undefined) return false;
    if (!('nodes' in value) || value['nodes'] === undefined) return false;
    return true;
}

export function SoundboardGraphResponse1FromJSON(json: any): SoundboardGraphResponse1 {
    return SoundboardGraphResponse1FromJSONTyped(json, false);
}

export function SoundboardGraphResponse1FromJSONTyped(json: any, ignoreDiscriminator: boolean): SoundboardGraphResponse1 {
    if (json == null) {
        return json;
    }
    return {
        
        'edges': json['edges'],
        'nodes': json['nodes'],
    };
}

export function SoundboardGraphResponse1ToJSON(json: any): SoundboardGraphResponse1 {
    return SoundboardGraphResponse1ToJSONTyped(json, false);
}

export function SoundboardGraphResponse1ToJSONTyped(value?: SoundboardGraphResponse1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'edges': value['edges'],
        'nodes': value['nodes'],
    };
}

