/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response for a source control action.
 * @export
 * @interface SourceActionResponse
 */
export interface SourceActionResponse {
    /**
     * 
     * @type {string}
     * @memberof SourceActionResponse
     */
    error?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SourceActionResponse
     */
    layerId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SourceActionResponse
     */
    nodeId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SourceActionResponse
     */
    status: string;
}

/**
 * Check if a given object implements the SourceActionResponse interface.
 */
export function instanceOfSourceActionResponse(value: object): value is SourceActionResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function SourceActionResponseFromJSON(json: any): SourceActionResponse {
    return SourceActionResponseFromJSONTyped(json, false);
}

export function SourceActionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceActionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
        'layerId': json['layer_id'] == null ? undefined : json['layer_id'],
        'nodeId': json['node_id'] == null ? undefined : json['node_id'],
        'status': json['status'],
    };
}

export function SourceActionResponseToJSON(json: any): SourceActionResponse {
    return SourceActionResponseToJSONTyped(json, false);
}

export function SourceActionResponseToJSONTyped(value?: SourceActionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'layer_id': value['layerId'],
        'node_id': value['nodeId'],
        'status': value['status'],
    };
}

