/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request to set a source's volume.
 * @export
 * @interface SourceVolumeRequest
 */
export interface SourceVolumeRequest {
    /**
     * 
     * @type {string}
     * @memberof SourceVolumeRequest
     */
    guildId: string;
    /**
     * 
     * @type {string}
     * @memberof SourceVolumeRequest
     */
    nodeId: string;
    /**
     * 
     * @type {number}
     * @memberof SourceVolumeRequest
     */
    volume: number;
}

/**
 * Check if a given object implements the SourceVolumeRequest interface.
 */
export function instanceOfSourceVolumeRequest(value: object): value is SourceVolumeRequest {
    if (!('guildId' in value) || value['guildId'] === undefined) return false;
    if (!('nodeId' in value) || value['nodeId'] === undefined) return false;
    if (!('volume' in value) || value['volume'] === undefined) return false;
    return true;
}

export function SourceVolumeRequestFromJSON(json: any): SourceVolumeRequest {
    return SourceVolumeRequestFromJSONTyped(json, false);
}

export function SourceVolumeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceVolumeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'guildId': json['guild_id'],
        'nodeId': json['node_id'],
        'volume': json['volume'],
    };
}

export function SourceVolumeRequestToJSON(json: any): SourceVolumeRequest {
    return SourceVolumeRequestToJSONTyped(json, false);
}

export function SourceVolumeRequestToJSONTyped(value?: SourceVolumeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'guild_id': value['guildId'],
        'node_id': value['nodeId'],
        'volume': value['volume'],
    };
}

