/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response for a volume change.
 * @export
 * @interface SourceVolumeResponse
 */
export interface SourceVolumeResponse {
    /**
     * 
     * @type {string}
     * @memberof SourceVolumeResponse
     */
    error?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SourceVolumeResponse
     */
    nodeId: string;
    /**
     * 
     * @type {string}
     * @memberof SourceVolumeResponse
     */
    status: string;
    /**
     * 
     * @type {number}
     * @memberof SourceVolumeResponse
     */
    volume: number;
}

/**
 * Check if a given object implements the SourceVolumeResponse interface.
 */
export function instanceOfSourceVolumeResponse(value: object): value is SourceVolumeResponse {
    if (!('nodeId' in value) || value['nodeId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('volume' in value) || value['volume'] === undefined) return false;
    return true;
}

export function SourceVolumeResponseFromJSON(json: any): SourceVolumeResponse {
    return SourceVolumeResponseFromJSONTyped(json, false);
}

export function SourceVolumeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceVolumeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
        'nodeId': json['node_id'],
        'status': json['status'],
        'volume': json['volume'],
    };
}

export function SourceVolumeResponseToJSON(json: any): SourceVolumeResponse {
    return SourceVolumeResponseToJSONTyped(json, false);
}

export function SourceVolumeResponseToJSONTyped(value?: SourceVolumeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'node_id': value['nodeId'],
        'status': value['status'],
        'volume': value['volume'],
    };
}

