/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request to start playing a source.
 * @export
 * @interface StartSourceRequest
 */
export interface StartSourceRequest {
    /**
     * 
     * @type {string}
     * @memberof StartSourceRequest
     */
    channelId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof StartSourceRequest
     */
    guildId: string;
    /**
     * 
     * @type {string}
     * @memberof StartSourceRequest
     */
    nodeId: string;
    /**
     * 
     * @type {string}
     * @memberof StartSourceRequest
     */
    url: string;
    /**
     * 
     * @type {number}
     * @memberof StartSourceRequest
     */
    volume?: number;
}

/**
 * Check if a given object implements the StartSourceRequest interface.
 */
export function instanceOfStartSourceRequest(value: object): value is StartSourceRequest {
    if (!('guildId' in value) || value['guildId'] === undefined) return false;
    if (!('nodeId' in value) || value['nodeId'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function StartSourceRequestFromJSON(json: any): StartSourceRequest {
    return StartSourceRequestFromJSONTyped(json, false);
}

export function StartSourceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartSourceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'channelId': json['channel_id'] == null ? undefined : json['channel_id'],
        'guildId': json['guild_id'],
        'nodeId': json['node_id'],
        'url': json['url'],
        'volume': json['volume'] == null ? undefined : json['volume'],
    };
}

export function StartSourceRequestToJSON(json: any): StartSourceRequest {
    return StartSourceRequestToJSONTyped(json, false);
}

export function StartSourceRequestToJSONTyped(value?: StartSourceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'channel_id': value['channelId'],
        'guild_id': value['guildId'],
        'node_id': value['nodeId'],
        'url': value['url'],
        'volume': value['volume'],
    };
}

