/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request to start a graph node.
 * @export
 * @interface StartNodeRequest
 */
export interface StartNodeRequest {
    /**
     * 
     * @type {string}
     * @memberof StartNodeRequest
     */
    guildId: string;
    /**
     * 
     * @type {boolean}
     * @memberof StartNodeRequest
     */
    loop?: boolean;
    /**
     * 
     * @type {string}
     * @memberof StartNodeRequest
     */
    nodeId: string;
    /**
     * 
     * @type {string}
     * @memberof StartNodeRequest
     */
    url: string;
    /**
     * 
     * @type {number}
     * @memberof StartNodeRequest
     */
    volume?: number;
}

/**
 * Check if a given object implements the StartNodeRequest interface.
 */
export function instanceOfStartNodeRequest(value: object): value is StartNodeRequest {
    if (!('guildId' in value) || value['guildId'] === undefined) return false;
    if (!('nodeId' in value) || value['nodeId'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function StartNodeRequestFromJSON(json: any): StartNodeRequest {
    return StartNodeRequestFromJSONTyped(json, false);
}

export function StartNodeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartNodeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'guildId': json['guild_id'],
        'loop': json['loop'] == null ? undefined : json['loop'],
        'nodeId': json['node_id'],
        'url': json['url'],
        'volume': json['volume'] == null ? undefined : json['volume'],
    };
}

export function StartNodeRequestToJSON(json: any): StartNodeRequest {
    return StartNodeRequestToJSONTyped(json, false);
}

export function StartNodeRequestToJSONTyped(value?: StartNodeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'guild_id': value['guildId'],
        'loop': value['loop'],
        'node_id': value['nodeId'],
        'url': value['url'],
        'volume': value['volume'],
    };
}

