/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StopNodeRequest
 */
export interface StopNodeRequest {
    /**
     * 
     * @type {string}
     * @memberof StopNodeRequest
     */
    guildId: string;
    /**
     * 
     * @type {string}
     * @memberof StopNodeRequest
     */
    nodeId: string;
}

/**
 * Check if a given object implements the StopNodeRequest interface.
 */
export function instanceOfStopNodeRequest(value: object): value is StopNodeRequest {
    if (!('guildId' in value) || value['guildId'] === undefined) return false;
    if (!('nodeId' in value) || value['nodeId'] === undefined) return false;
    return true;
}

export function StopNodeRequestFromJSON(json: any): StopNodeRequest {
    return StopNodeRequestFromJSONTyped(json, false);
}

export function StopNodeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StopNodeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'guildId': json['guild_id'],
        'nodeId': json['node_id'],
    };
}

export function StopNodeRequestToJSON(json: any): StopNodeRequest {
    return StopNodeRequestToJSONTyped(json, false);
}

export function StopNodeRequestToJSONTyped(value?: StopNodeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'guild_id': value['guildId'],
        'node_id': value['nodeId'],
    };
}

