/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StopSourceRequest
 */
export interface StopSourceRequest {
    /**
     * 
     * @type {string}
     * @memberof StopSourceRequest
     */
    guildId: string;
    /**
     * 
     * @type {string}
     * @memberof StopSourceRequest
     */
    nodeId: string;
}

/**
 * Check if a given object implements the StopSourceRequest interface.
 */
export function instanceOfStopSourceRequest(value: object): value is StopSourceRequest {
    if (!('guildId' in value) || value['guildId'] === undefined) return false;
    if (!('nodeId' in value) || value['nodeId'] === undefined) return false;
    return true;
}

export function StopSourceRequestFromJSON(json: any): StopSourceRequest {
    return StopSourceRequestFromJSONTyped(json, false);
}

export function StopSourceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StopSourceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'guildId': json['guild_id'],
        'nodeId': json['node_id'],
    };
}

export function StopSourceRequestToJSON(json: any): StopSourceRequest {
    return StopSourceRequestToJSONTyped(json, false);
}

export function StopSourceRequestToJSONTyped(value?: StopSourceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'guild_id': value['guildId'],
        'node_id': value['nodeId'],
    };
}

