/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatePresetRequest
 */
export interface UpdatePresetRequest {
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof UpdatePresetRequest
     */
    edges?: Array<{ [key: string]: any; }> | null;
    /**
     * 
     * @type {number}
     * @memberof UpdatePresetRequest
     */
    guildId: number;
    /**
     * 
     * @type {string}
     * @memberof UpdatePresetRequest
     */
    name?: string | null;
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof UpdatePresetRequest
     */
    nodes?: Array<{ [key: string]: any; }> | null;
}

/**
 * Check if a given object implements the UpdatePresetRequest interface.
 */
export function instanceOfUpdatePresetRequest(value: object): value is UpdatePresetRequest {
    if (!('guildId' in value) || value['guildId'] === undefined) return false;
    return true;
}

export function UpdatePresetRequestFromJSON(json: any): UpdatePresetRequest {
    return UpdatePresetRequestFromJSONTyped(json, false);
}

export function UpdatePresetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePresetRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'edges': json['edges'] == null ? undefined : json['edges'],
        'guildId': json['guild_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'nodes': json['nodes'] == null ? undefined : json['nodes'],
    };
}

export function UpdatePresetRequestToJSON(json: any): UpdatePresetRequest {
    return UpdatePresetRequestToJSONTyped(json, false);
}

export function UpdatePresetRequestToJSONTyped(value?: UpdatePresetRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'edges': value['edges'],
        'guild_id': value['guildId'],
        'name': value['name'],
        'nodes': value['nodes'],
    };
}

