/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request to update the soundboard graph.
 * @export
 * @interface UpdateGraphRequest
 */
export interface UpdateGraphRequest {
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof UpdateGraphRequest
     */
    edges: Array<{ [key: string]: any; }>;
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof UpdateGraphRequest
     */
    nodes: Array<{ [key: string]: any; }>;
}

/**
 * Check if a given object implements the UpdateGraphRequest interface.
 */
export function instanceOfUpdateGraphRequest(value: object): value is UpdateGraphRequest {
    if (!('edges' in value) || value['edges'] === undefined) return false;
    if (!('nodes' in value) || value['nodes'] === undefined) return false;
    return true;
}

export function UpdateGraphRequestFromJSON(json: any): UpdateGraphRequest {
    return UpdateGraphRequestFromJSONTyped(json, false);
}

export function UpdateGraphRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateGraphRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'edges': json['edges'],
        'nodes': json['nodes'],
    };
}

export function UpdateGraphRequestToJSON(json: any): UpdateGraphRequest {
    return UpdateGraphRequestToJSONTyped(json, false);
}

export function UpdateGraphRequestToJSONTyped(value?: UpdateGraphRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'edges': value['edges'],
        'nodes': value['nodes'],
    };
}

