/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request to change volume.
 * @export
 * @interface VolumeRequest
 */
export interface VolumeRequest {
    /**
     * 
     * @type {string}
     * @memberof VolumeRequest
     */
    guildId: string;
    /**
     * 
     * @type {number}
     * @memberof VolumeRequest
     */
    volume: number;
}

/**
 * Check if a given object implements the VolumeRequest interface.
 */
export function instanceOfVolumeRequest(value: object): value is VolumeRequest {
    if (!('guildId' in value) || value['guildId'] === undefined) return false;
    if (!('volume' in value) || value['volume'] === undefined) return false;
    return true;
}

export function VolumeRequestFromJSON(json: any): VolumeRequest {
    return VolumeRequestFromJSONTyped(json, false);
}

export function VolumeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VolumeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'guildId': json['guild_id'],
        'volume': json['volume'],
    };
}

export function VolumeRequestToJSON(json: any): VolumeRequest {
    return VolumeRequestToJSONTyped(json, false);
}

export function VolumeRequestToJSONTyped(value?: VolumeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'guild_id': value['guildId'],
        'volume': value['volume'],
    };
}

