"""
This type stub file was generated by pyright.
"""

from typing import List
from typing_extensions import TypedDict

__all__ = ["CitationMetadataDict", "CitationSourceDict"]
class CitationSourceDict(TypedDict):
    start_index: int | None
    end_index: int | None
    uri: str | None
    license: str | None
    __doc__ = ...


class CitationMetadataDict(TypedDict):
    citation_sources: List[CitationSourceDict | None]
    __doc__ = ...


