"""
This type stub file was generated by pyright.
"""

from typing_extensions import TypedDict

class EmbeddingDict(TypedDict):
    embedding: list[float]
    ...


class BatchEmbeddingDict(TypedDict):
    embedding: list[list[float]]
    ...


