services:
  harpi-backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    volumes:
      - .:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - harpi-net

  harpi-frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    command: bash -c "cd frontend && bun install && bun run dev"
    networks:
      - harpi-net

networks:
  harpi-net:
    driver: bridge
