"""
This type stub file was generated by pyright.
"""

import logging
from typing import Any

"""Helper functions for commonly used utilities."""
async def response_log_async(logger: logging.Logger, response: Any) -> None:
    """
    Logs an Async HTTP response at the DEBUG level if logging is enabled.

    Args:
        logger: The logging.Logger instance to use.
        response: The HTTP response object to log.
    """
    ...

