"""
This type stub file was generated by pyright.
"""

import logging
from typing import List, Optional

_LOGGING_INITIALIZED = ...
_BASE_LOGGER_NAME = ...
_recognized_logging_fields = ...
def logger_configured(logger) -> bool:
    """Determines whether `logger` has non-default configuration

    Args:
      logger: The logger to check.

    Returns:
      bool: Whether the logger has any non-default configuration.
    """
    ...

def initialize_logging(): # -> None:
    """Initializes "google" loggers, partly based on the environment variable

    Initializes the "google" logger and any loggers (at the "google"
    level or lower) specified by the environment variable
    GOOGLE_SDK_PYTHON_LOGGING_SCOPE, as long as none of these loggers
    were previously configured. If any such loggers (including the
    "google" logger) are initialized, they are set to NOT propagate
    log events up to their parent loggers.

    This initialization is executed only once, and hence the
    environment variable is only processed the first time this
    function is called.
    """
    ...

def parse_logging_scopes(scopes: Optional[str] = ...) -> List[str]:
    """Returns a list of logger names.

    Splits the single string of comma-separated logger names into a list of individual logger name strings.

    Args:
      scopes: The name of a single logger. (In the future, this will be a comma-separated list of multiple loggers.)

    Returns:
      A list of all the logger names in scopes.
    """
    ...

def configure_defaults(logger): # -> None:
    """Configures `logger` to emit structured info to stdout."""
    ...

def setup_logging(scopes: str = ...): # -> None:
    """Sets up logging for the specified `scopes`.

    If the loggers specified in `scopes` have not been previously
    configured, this will configure them to emit structured log
    entries to stdout, and to not propagate their log events to their
    parent loggers. Additionally, if the "google" logger (whether it
    was specified in `scopes` or not) was not previously configured,
    it will also configure it to not propagate log events to the root
    logger.

    Args:
      scopes: The name of a single logger. (In the future, this will be a comma-separated list of multiple loggers.)

    """
    ...

class StructuredLogFormatter(logging.Formatter):
    def format(self, record: logging.LogRecord): # -> str:
        ...
    


