/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ChannelSelectResponse,
  ChannelsResponse,
  ConnectSoundboardRequest,
  ConnectionResponse,
  CreatePresetRequest,
  GuildResponse,
  GuildSelectResponse,
  MetadataRequest,
  MetadataResponse,
  MusicAddRequest,
  MusicAddResponse,
  MusicControlRequest,
  MusicControlResponse,
  MusicStatusResponse,
  NodeLoopRequest,
  NodeVolumeRequest,
  PresetListResponse,
  PresetResponse,
  SelectChannelRequest,
  SelectGuildRequest,
  ServerStatusModel,
  SoundboardGraphResponse1,
  SoundboardGraphResponse2,
  SoundboardStatusResponse,
  SourceActionResponse,
  SourceVolumeRequest,
  SourceVolumeResponse,
  StartNodeRequest,
  StartSourceRequest,
  StatusResponse,
  StopNodeRequest,
  StopSourceRequest,
  UpdateGraphRequest,
  UpdatePresetRequest,
} from '../models/index';
import {
    ChannelSelectResponseFromJSON,
    ChannelSelectResponseToJSON,
    ChannelsResponseFromJSON,
    ChannelsResponseToJSON,
    ConnectSoundboardRequestFromJSON,
    ConnectSoundboardRequestToJSON,
    ConnectionResponseFromJSON,
    ConnectionResponseToJSON,
    CreatePresetRequestFromJSON,
    CreatePresetRequestToJSON,
    GuildResponseFromJSON,
    GuildResponseToJSON,
    GuildSelectResponseFromJSON,
    GuildSelectResponseToJSON,
    MetadataRequestFromJSON,
    MetadataRequestToJSON,
    MetadataResponseFromJSON,
    MetadataResponseToJSON,
    MusicAddRequestFromJSON,
    MusicAddRequestToJSON,
    MusicAddResponseFromJSON,
    MusicAddResponseToJSON,
    MusicControlRequestFromJSON,
    MusicControlRequestToJSON,
    MusicControlResponseFromJSON,
    MusicControlResponseToJSON,
    MusicStatusResponseFromJSON,
    MusicStatusResponseToJSON,
    NodeLoopRequestFromJSON,
    NodeLoopRequestToJSON,
    NodeVolumeRequestFromJSON,
    NodeVolumeRequestToJSON,
    PresetListResponseFromJSON,
    PresetListResponseToJSON,
    PresetResponseFromJSON,
    PresetResponseToJSON,
    SelectChannelRequestFromJSON,
    SelectChannelRequestToJSON,
    SelectGuildRequestFromJSON,
    SelectGuildRequestToJSON,
    ServerStatusModelFromJSON,
    ServerStatusModelToJSON,
    SoundboardGraphResponse1FromJSON,
    SoundboardGraphResponse1ToJSON,
    SoundboardGraphResponse2FromJSON,
    SoundboardGraphResponse2ToJSON,
    SoundboardStatusResponseFromJSON,
    SoundboardStatusResponseToJSON,
    SourceActionResponseFromJSON,
    SourceActionResponseToJSON,
    SourceVolumeRequestFromJSON,
    SourceVolumeRequestToJSON,
    SourceVolumeResponseFromJSON,
    SourceVolumeResponseToJSON,
    StartNodeRequestFromJSON,
    StartNodeRequestToJSON,
    StartSourceRequestFromJSON,
    StartSourceRequestToJSON,
    StatusResponseFromJSON,
    StatusResponseToJSON,
    StopNodeRequestFromJSON,
    StopNodeRequestToJSON,
    StopSourceRequestFromJSON,
    StopSourceRequestToJSON,
    UpdateGraphRequestFromJSON,
    UpdateGraphRequestToJSON,
    UpdatePresetRequestFromJSON,
    UpdatePresetRequestToJSON,
} from '../models/index';

export interface DeleteDeletePresetRequest {
    presetId: string;
}

export interface GetGetChannelsRequest {
    guildId: string | null;
}

export interface GetGetPresetRequest {
    presetId: string | null;
}

export interface GetGetSoundboardGraphRequest {
    guildId: number;
}

export interface GetGetSoundboardStatusRequest {
    guildId: number;
}

export interface GetMusicStatusRequest {
    guildId: string;
}

export interface PostConnectSoundboardRequest {
    guildId: number | null;
    connectSoundboardRequest?: ConnectSoundboardRequest;
}

export interface PostCreatePresetRequest {
    createPresetRequest?: CreatePresetRequest;
}

export interface PostDisconnectSoundboardRequest {
    guildId: number;
}

export interface PostFetchNodeMetadataRequest {
    metadataRequest?: MetadataRequest;
}

export interface PostMusicAddRequest {
    musicAddRequest?: MusicAddRequest;
}

export interface PostMusicControlRequest {
    musicControlRequest?: MusicControlRequest;
}

export interface PostSelectChannelRequest {
    selectChannelRequest?: SelectChannelRequest;
}

export interface PostSelectGuildRequest {
    selectGuildRequest?: SelectGuildRequest;
}

export interface PostSetNodeLoopRequest {
    nodeLoopRequest?: NodeLoopRequest;
}

export interface PostSetNodeVolumeRequest {
    nodeVolumeRequest?: NodeVolumeRequest;
}

export interface PostSetSourceVolumeRequest {
    sourceVolumeRequest?: SourceVolumeRequest;
}

export interface PostStartNodeRequest {
    startNodeRequest?: StartNodeRequest;
}

export interface PostStartSourceRequest {
    startSourceRequest?: StartSourceRequest;
}

export interface PostStopAllSourcesRequest {
    guildId: number;
}

export interface PostStopNodeRequest {
    stopNodeRequest?: StopNodeRequest;
}

export interface PostStopSourceRequest {
    stopSourceRequest?: StopSourceRequest;
}

export interface PutUpdatePresetRequest {
    presetId: string;
    updatePresetRequest?: UpdatePresetRequest;
}

export interface PutUpdateSoundboardGraphRequest {
    guildId: number;
    updateGraphRequest?: UpdateGraphRequest;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Creates request options for deleteDeletePreset without sending the request
     */
    async deleteDeletePresetRequestOpts(requestParameters: DeleteDeletePresetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['presetId'] == null) {
            throw new runtime.RequiredError(
                'presetId',
                'Required parameter "presetId" was null or undefined when calling deleteDeletePreset().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/soundboard/presets/{preset_id}`;
        urlPath = urlPath.replace(`{${"preset_id"}}`, encodeURIComponent(String(requestParameters['presetId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 
     * Delete a preset.
     */
    async deleteDeletePresetRaw(requestParameters: DeleteDeletePresetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StatusResponse>> {
        const requestOptions = await this.deleteDeletePresetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StatusResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Delete a preset.
     */
    async deleteDeletePreset(requestParameters: DeleteDeletePresetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StatusResponse> {
        const response = await this.deleteDeletePresetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getApiServerstatus without sending the request
     */
    async getApiServerstatusRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/serverstatus`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getApiServerstatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServerStatusModel>> {
        const requestOptions = await this.getApiServerstatusRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServerStatusModelFromJSON(jsonValue));
    }

    /**
     */
    async getApiServerstatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServerStatusModel> {
        const response = await this.getApiServerstatusRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGetChannels without sending the request
     */
    async getGetChannelsRequestOpts(requestParameters: GetGetChannelsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['guildId'] == null) {
            throw new runtime.RequiredError(
                'guildId',
                'Required parameter "guildId" was null or undefined when calling getGetChannels().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/guild/{guild_id}/channels`;
        urlPath = urlPath.replace(`{${"guild_id"}}`, encodeURIComponent(String(requestParameters['guildId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getGetChannelsRaw(requestParameters: GetGetChannelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChannelsResponse>> {
        const requestOptions = await this.getGetChannelsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChannelsResponseFromJSON(jsonValue));
    }

    /**
     */
    async getGetChannels(requestParameters: GetGetChannelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChannelsResponse> {
        const response = await this.getGetChannelsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGetGuilds without sending the request
     */
    async getGetGuildsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/guild`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getGetGuildsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GuildResponse>>> {
        const requestOptions = await this.getGetGuildsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GuildResponseFromJSON));
    }

    /**
     */
    async getGetGuilds(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GuildResponse>> {
        const response = await this.getGetGuildsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGetPreset without sending the request
     */
    async getGetPresetRequestOpts(requestParameters: GetGetPresetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['presetId'] == null) {
            throw new runtime.RequiredError(
                'presetId',
                'Required parameter "presetId" was null or undefined when calling getGetPreset().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/soundboard/presets/{preset_id}`;
        urlPath = urlPath.replace(`{${"preset_id"}}`, encodeURIComponent(String(requestParameters['presetId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 
     * Get a specific preset.
     */
    async getGetPresetRaw(requestParameters: GetGetPresetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PresetResponse>> {
        const requestOptions = await this.getGetPresetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PresetResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Get a specific preset.
     */
    async getGetPreset(requestParameters: GetGetPresetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PresetResponse> {
        const response = await this.getGetPresetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGetSoundboardGraph without sending the request
     */
    async getGetSoundboardGraphRequestOpts(requestParameters: GetGetSoundboardGraphRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['guildId'] == null) {
            throw new runtime.RequiredError(
                'guildId',
                'Required parameter "guildId" was null or undefined when calling getGetSoundboardGraph().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/soundboard/graph/{guild_id}`;
        urlPath = urlPath.replace(`{${"guild_id"}}`, encodeURIComponent(String(requestParameters['guildId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 
     * Get the current soundboard graph for a guild.
     */
    async getGetSoundboardGraphRaw(requestParameters: GetGetSoundboardGraphRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SoundboardGraphResponse1>> {
        const requestOptions = await this.getGetSoundboardGraphRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SoundboardGraphResponse1FromJSON(jsonValue));
    }

    /**
     * 
     * Get the current soundboard graph for a guild.
     */
    async getGetSoundboardGraph(requestParameters: GetGetSoundboardGraphRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SoundboardGraphResponse1> {
        const response = await this.getGetSoundboardGraphRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGetSoundboardStatus without sending the request
     */
    async getGetSoundboardStatusRequestOpts(requestParameters: GetGetSoundboardStatusRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['guildId'] == null) {
            throw new runtime.RequiredError(
                'guildId',
                'Required parameter "guildId" was null or undefined when calling getGetSoundboardStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/soundboard/status/{guild_id}`;
        urlPath = urlPath.replace(`{${"guild_id"}}`, encodeURIComponent(String(requestParameters['guildId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 
     * Get soundboard connection and playback status.
     */
    async getGetSoundboardStatusRaw(requestParameters: GetGetSoundboardStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SoundboardStatusResponse>> {
        const requestOptions = await this.getGetSoundboardStatusRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SoundboardStatusResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Get soundboard connection and playback status.
     */
    async getGetSoundboardStatus(requestParameters: GetGetSoundboardStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SoundboardStatusResponse> {
        const response = await this.getGetSoundboardStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getListPresets without sending the request
     */
    async getListPresetsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/soundboard/presets`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 
     * List all presets for a guild.
     */
    async getListPresetsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PresetListResponse>>> {
        const requestOptions = await this.getListPresetsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PresetListResponseFromJSON));
    }

    /**
     * 
     * List all presets for a guild.
     */
    async getListPresets(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PresetListResponse>> {
        const response = await this.getListPresetsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMusicStatus without sending the request
     */
    async getMusicStatusRequestOpts(requestParameters: GetMusicStatusRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['guildId'] == null) {
            throw new runtime.RequiredError(
                'guildId',
                'Required parameter "guildId" was null or undefined when calling getMusicStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/music/{guild_id}/status`;
        urlPath = urlPath.replace(`{${"guild_id"}}`, encodeURIComponent(String(requestParameters['guildId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     *  Query params:     guild_id: The guild ID to get status for.  Returns:     JSON with music data or error.
     * Get music status for a guild.
     */
    async getMusicStatusRaw(requestParameters: GetMusicStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MusicStatusResponse>> {
        const requestOptions = await this.getMusicStatusRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MusicStatusResponseFromJSON(jsonValue));
    }

    /**
     *  Query params:     guild_id: The guild ID to get status for.  Returns:     JSON with music data or error.
     * Get music status for a guild.
     */
    async getMusicStatus(requestParameters: GetMusicStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MusicStatusResponse> {
        const response = await this.getMusicStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postConnectSoundboard without sending the request
     */
    async postConnectSoundboardRequestOpts(requestParameters: PostConnectSoundboardRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['guildId'] == null) {
            throw new runtime.RequiredError(
                'guildId',
                'Required parameter "guildId" was null or undefined when calling postConnectSoundboard().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/soundboard/connect/{guild_id}`;
        urlPath = urlPath.replace(`{${"guild_id"}}`, encodeURIComponent(String(requestParameters['guildId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConnectSoundboardRequestToJSON(requestParameters['connectSoundboardRequest']),
        };
    }

    /**
     *  Body:     channel_id: The voice channel ID to connect to.
     * Connect to voice channel for soundboard playback.
     */
    async postConnectSoundboardRaw(requestParameters: PostConnectSoundboardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConnectionResponse>> {
        const requestOptions = await this.postConnectSoundboardRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConnectionResponseFromJSON(jsonValue));
    }

    /**
     *  Body:     channel_id: The voice channel ID to connect to.
     * Connect to voice channel for soundboard playback.
     */
    async postConnectSoundboard(requestParameters: PostConnectSoundboardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConnectionResponse> {
        const response = await this.postConnectSoundboardRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postCreatePreset without sending the request
     */
    async postCreatePresetRequestOpts(requestParameters: PostCreatePresetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/soundboard/presets`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePresetRequestToJSON(requestParameters['createPresetRequest']),
        };
    }

    /**
     * 
     * Create a new preset.
     */
    async postCreatePresetRaw(requestParameters: PostCreatePresetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PresetResponse>> {
        const requestOptions = await this.postCreatePresetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PresetResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Create a new preset.
     */
    async postCreatePreset(requestParameters: PostCreatePresetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PresetResponse> {
        const response = await this.postCreatePresetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postDisconnectSoundboard without sending the request
     */
    async postDisconnectSoundboardRequestOpts(requestParameters: PostDisconnectSoundboardRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['guildId'] == null) {
            throw new runtime.RequiredError(
                'guildId',
                'Required parameter "guildId" was null or undefined when calling postDisconnectSoundboard().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/soundboard/disconnect/{guild_id}`;
        urlPath = urlPath.replace(`{${"guild_id"}}`, encodeURIComponent(String(requestParameters['guildId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 
     * Disconnect soundboard from voice channel.
     */
    async postDisconnectSoundboardRaw(requestParameters: PostDisconnectSoundboardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.postDisconnectSoundboardRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * 
     * Disconnect soundboard from voice channel.
     */
    async postDisconnectSoundboard(requestParameters: PostDisconnectSoundboardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.postDisconnectSoundboardRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for postFetchNodeMetadata without sending the request
     */
    async postFetchNodeMetadataRequestOpts(requestParameters: PostFetchNodeMetadataRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/soundboard/node/metadata`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MetadataRequestToJSON(requestParameters['metadataRequest']),
        };
    }

    /**
     *  Body:     url: The audio URL (YouTube, etc).
     * Fetch metadata for a URL without starting playback.
     */
    async postFetchNodeMetadataRaw(requestParameters: PostFetchNodeMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MetadataResponse>> {
        const requestOptions = await this.postFetchNodeMetadataRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MetadataResponseFromJSON(jsonValue));
    }

    /**
     *  Body:     url: The audio URL (YouTube, etc).
     * Fetch metadata for a URL without starting playback.
     */
    async postFetchNodeMetadata(requestParameters: PostFetchNodeMetadataRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MetadataResponse> {
        const response = await this.postFetchNodeMetadataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postMusicAdd without sending the request
     */
    async postMusicAddRequestOpts(requestParameters: PostMusicAddRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/music/add`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MusicAddRequestToJSON(requestParameters['musicAddRequest']),
        };
    }

    /**
     *  Body:     guild_id: The guild ID.     channel_id: The voice channel ID to connect to.     link: The music URL (YouTube, etc).     type: (Optional) \'queue\' (default) or \'layer\'.  Returns:     JSON with status or error.
     * Add music to queue via link.
     */
    async postMusicAddRaw(requestParameters: PostMusicAddRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MusicAddResponse>> {
        const requestOptions = await this.postMusicAddRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MusicAddResponseFromJSON(jsonValue));
    }

    /**
     *  Body:     guild_id: The guild ID.     channel_id: The voice channel ID to connect to.     link: The music URL (YouTube, etc).     type: (Optional) \'queue\' (default) or \'layer\'.  Returns:     JSON with status or error.
     * Add music to queue via link.
     */
    async postMusicAdd(requestParameters: PostMusicAddRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MusicAddResponse> {
        const response = await this.postMusicAddRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postMusicControl without sending the request
     */
    async postMusicControlRequestOpts(requestParameters: PostMusicControlRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/music/control`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MusicControlRequestToJSON(requestParameters['musicControlRequest']),
        };
    }

    /**
     *  Body:     guild_id: The guild ID.     action: One of \'stop\', \'skip\', \'pause\', \'resume\', \'loop\'.     mode: (Optional) Loop mode for \'loop\' action.  Returns:     JSON with status or error.
     * Control music playback for a guild.
     */
    async postMusicControlRaw(requestParameters: PostMusicControlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MusicControlResponse>> {
        const requestOptions = await this.postMusicControlRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MusicControlResponseFromJSON(jsonValue));
    }

    /**
     *  Body:     guild_id: The guild ID.     action: One of \'stop\', \'skip\', \'pause\', \'resume\', \'loop\'.     mode: (Optional) Loop mode for \'loop\' action.  Returns:     JSON with status or error.
     * Control music playback for a guild.
     */
    async postMusicControl(requestParameters: PostMusicControlRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MusicControlResponse> {
        const response = await this.postMusicControlRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postSelectChannel without sending the request
     */
    async postSelectChannelRequestOpts(requestParameters: PostSelectChannelRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/guild/channel`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SelectChannelRequestToJSON(requestParameters['selectChannelRequest']),
        };
    }

    /**
     */
    async postSelectChannelRaw(requestParameters: PostSelectChannelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChannelSelectResponse>> {
        const requestOptions = await this.postSelectChannelRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChannelSelectResponseFromJSON(jsonValue));
    }

    /**
     */
    async postSelectChannel(requestParameters: PostSelectChannelRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChannelSelectResponse> {
        const response = await this.postSelectChannelRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postSelectGuild without sending the request
     */
    async postSelectGuildRequestOpts(requestParameters: PostSelectGuildRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/guild`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SelectGuildRequestToJSON(requestParameters['selectGuildRequest']),
        };
    }

    /**
     */
    async postSelectGuildRaw(requestParameters: PostSelectGuildRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GuildSelectResponse>> {
        const requestOptions = await this.postSelectGuildRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GuildSelectResponseFromJSON(jsonValue));
    }

    /**
     */
    async postSelectGuild(requestParameters: PostSelectGuildRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GuildSelectResponse> {
        const response = await this.postSelectGuildRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postSetNodeLoop without sending the request
     */
    async postSetNodeLoopRequestOpts(requestParameters: PostSetNodeLoopRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/soundboard/node/loop`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NodeLoopRequestToJSON(requestParameters['nodeLoopRequest']),
        };
    }

    /**
     *  Body:     guild_id: The guild ID.     node_id: The node identifier.     loop: Whether to loop the audio.
     * Set loop for a node.
     */
    async postSetNodeLoopRaw(requestParameters: PostSetNodeLoopRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SourceActionResponse>> {
        const requestOptions = await this.postSetNodeLoopRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SourceActionResponseFromJSON(jsonValue));
    }

    /**
     *  Body:     guild_id: The guild ID.     node_id: The node identifier.     loop: Whether to loop the audio.
     * Set loop for a node.
     */
    async postSetNodeLoop(requestParameters: PostSetNodeLoopRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SourceActionResponse> {
        const response = await this.postSetNodeLoopRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postSetNodeVolume without sending the request
     */
    async postSetNodeVolumeRequestOpts(requestParameters: PostSetNodeVolumeRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/soundboard/node/volume`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NodeVolumeRequestToJSON(requestParameters['nodeVolumeRequest']),
        };
    }

    /**
     *  Body:     guild_id: The guild ID.     node_id: The node identifier.     volume: Volume level (0-200).
     * Set volume for a node.
     */
    async postSetNodeVolumeRaw(requestParameters: PostSetNodeVolumeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SourceVolumeResponse>> {
        const requestOptions = await this.postSetNodeVolumeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SourceVolumeResponseFromJSON(jsonValue));
    }

    /**
     *  Body:     guild_id: The guild ID.     node_id: The node identifier.     volume: Volume level (0-200).
     * Set volume for a node.
     */
    async postSetNodeVolume(requestParameters: PostSetNodeVolumeRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SourceVolumeResponse> {
        const response = await this.postSetNodeVolumeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postSetSourceVolume without sending the request
     */
    async postSetSourceVolumeRequestOpts(requestParameters: PostSetSourceVolumeRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/soundboard/source/volume`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SourceVolumeRequestToJSON(requestParameters['sourceVolumeRequest']),
        };
    }

    /**
     *  Body:     guild_id: The guild ID.     node_id: The node identifier.     volume: Volume level (0-200).
     * Set volume for a source.
     */
    async postSetSourceVolumeRaw(requestParameters: PostSetSourceVolumeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SourceVolumeResponse>> {
        const requestOptions = await this.postSetSourceVolumeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SourceVolumeResponseFromJSON(jsonValue));
    }

    /**
     *  Body:     guild_id: The guild ID.     node_id: The node identifier.     volume: Volume level (0-200).
     * Set volume for a source.
     */
    async postSetSourceVolume(requestParameters: PostSetSourceVolumeRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SourceVolumeResponse> {
        const response = await this.postSetSourceVolumeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postStartNode without sending the request
     */
    async postStartNodeRequestOpts(requestParameters: PostStartNodeRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/soundboard/node/start`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StartNodeRequestToJSON(requestParameters['startNodeRequest']),
        };
    }

    /**
     *  Body:     guild_id: The guild ID.     node_id: Unique node identifier for this source.     url: The audio URL.     volume: Initial volume (0-200, default 100).     loop: Whether to loop the audio (default false).
     * Prepare a sound source node (load but don\'t play yet).
     */
    async postStartNodeRaw(requestParameters: PostStartNodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SourceActionResponse>> {
        const requestOptions = await this.postStartNodeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SourceActionResponseFromJSON(jsonValue));
    }

    /**
     *  Body:     guild_id: The guild ID.     node_id: Unique node identifier for this source.     url: The audio URL.     volume: Initial volume (0-200, default 100).     loop: Whether to loop the audio (default false).
     * Prepare a sound source node (load but don\'t play yet).
     */
    async postStartNode(requestParameters: PostStartNodeRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SourceActionResponse> {
        const response = await this.postStartNodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postStartSource without sending the request
     */
    async postStartSourceRequestOpts(requestParameters: PostStartSourceRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/soundboard/source/start`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StartSourceRequestToJSON(requestParameters['startSourceRequest']),
        };
    }

    /**
     *  Body:     guild_id: The guild ID.     channel_id: The voice channel ID (required if not connected).     node_id: Unique node identifier for this source.     url: The audio URL.     volume: Initial volume (0-200, default 100).
     * Start playing a source (adds as background layer).
     */
    async postStartSourceRaw(requestParameters: PostStartSourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SourceActionResponse>> {
        const requestOptions = await this.postStartSourceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SourceActionResponseFromJSON(jsonValue));
    }

    /**
     *  Body:     guild_id: The guild ID.     channel_id: The voice channel ID (required if not connected).     node_id: Unique node identifier for this source.     url: The audio URL.     volume: Initial volume (0-200, default 100).
     * Start playing a source (adds as background layer).
     */
    async postStartSource(requestParameters: PostStartSourceRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SourceActionResponse> {
        const response = await this.postStartSourceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postStopAllSources without sending the request
     */
    async postStopAllSourcesRequestOpts(requestParameters: PostStopAllSourcesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['guildId'] == null) {
            throw new runtime.RequiredError(
                'guildId',
                'Required parameter "guildId" was null or undefined when calling postStopAllSources().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/soundboard/stop/{guild_id}`;
        urlPath = urlPath.replace(`{${"guild_id"}}`, encodeURIComponent(String(requestParameters['guildId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 
     * Stop all soundboard sources for a guild.
     */
    async postStopAllSourcesRaw(requestParameters: PostStopAllSourcesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StatusResponse>> {
        const requestOptions = await this.postStopAllSourcesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StatusResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Stop all soundboard sources for a guild.
     */
    async postStopAllSources(requestParameters: PostStopAllSourcesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StatusResponse> {
        const response = await this.postStopAllSourcesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postStopNode without sending the request
     */
    async postStopNodeRequestOpts(requestParameters: PostStopNodeRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/soundboard/node/stop`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StopNodeRequestToJSON(requestParameters['stopNodeRequest']),
        };
    }

    /**
     *  Body:     guild_id: The guild ID.     node_id: The node identifier to stop.
     * Stop a sound source node - stops playback and unloads.
     */
    async postStopNodeRaw(requestParameters: PostStopNodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SourceActionResponse>> {
        const requestOptions = await this.postStopNodeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SourceActionResponseFromJSON(jsonValue));
    }

    /**
     *  Body:     guild_id: The guild ID.     node_id: The node identifier to stop.
     * Stop a sound source node - stops playback and unloads.
     */
    async postStopNode(requestParameters: PostStopNodeRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SourceActionResponse> {
        const response = await this.postStopNodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postStopSource without sending the request
     */
    async postStopSourceRequestOpts(requestParameters: PostStopSourceRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/soundboard/source/stop`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StopSourceRequestToJSON(requestParameters['stopSourceRequest']),
        };
    }

    /**
     *  Body:     guild_id: The guild ID.     node_id: The node identifier to stop.
     * Stop a source (removes background layer).
     */
    async postStopSourceRaw(requestParameters: PostStopSourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SourceActionResponse>> {
        const requestOptions = await this.postStopSourceRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SourceActionResponseFromJSON(jsonValue));
    }

    /**
     *  Body:     guild_id: The guild ID.     node_id: The node identifier to stop.
     * Stop a source (removes background layer).
     */
    async postStopSource(requestParameters: PostStopSourceRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SourceActionResponse> {
        const response = await this.postStopSourceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for putUpdatePreset without sending the request
     */
    async putUpdatePresetRequestOpts(requestParameters: PutUpdatePresetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['presetId'] == null) {
            throw new runtime.RequiredError(
                'presetId',
                'Required parameter "presetId" was null or undefined when calling putUpdatePreset().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/soundboard/presets/{preset_id}`;
        urlPath = urlPath.replace(`{${"preset_id"}}`, encodeURIComponent(String(requestParameters['presetId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdatePresetRequestToJSON(requestParameters['updatePresetRequest']),
        };
    }

    /**
     * 
     * Update an existing preset.
     */
    async putUpdatePresetRaw(requestParameters: PutUpdatePresetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PresetResponse>> {
        const requestOptions = await this.putUpdatePresetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PresetResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Update an existing preset.
     */
    async putUpdatePreset(requestParameters: PutUpdatePresetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PresetResponse> {
        const response = await this.putUpdatePresetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for putUpdateSoundboardGraph without sending the request
     */
    async putUpdateSoundboardGraphRequestOpts(requestParameters: PutUpdateSoundboardGraphRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['guildId'] == null) {
            throw new runtime.RequiredError(
                'guildId',
                'Required parameter "guildId" was null or undefined when calling putUpdateSoundboardGraph().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/soundboard/graph/{guild_id}`;
        urlPath = urlPath.replace(`{${"guild_id"}}`, encodeURIComponent(String(requestParameters['guildId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateGraphRequestToJSON(requestParameters['updateGraphRequest']),
        };
    }

    /**
     * 
     * Update the soundboard graph for a guild.
     */
    async putUpdateSoundboardGraphRaw(requestParameters: PutUpdateSoundboardGraphRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SoundboardGraphResponse2>> {
        const requestOptions = await this.putUpdateSoundboardGraphRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SoundboardGraphResponse2FromJSON(jsonValue));
    }

    /**
     * 
     * Update the soundboard graph for a guild.
     */
    async putUpdateSoundboardGraph(requestParameters: PutUpdateSoundboardGraphRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SoundboardGraphResponse2> {
        const response = await this.putUpdateSoundboardGraphRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
