/* tslint:disable */
/* eslint-disable */
/**
 * app
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ChannelSelectResponse,
  ChannelsResponse,
  GuildRequest,
  GuildResponse,
  GuildSelectResponse,
  LayerRemoveRequest,
  LayerVolumeRequest,
  LoopRequest,
  MusicAddRequest,
  MusicAddResponse,
  MusicControlRequest,
  MusicControlResponse,
  MusicStatusResponse,
  SelectChannelRequest,
  SelectGuildRequest,
  ServerStatusModel,
  VolumeRequest,
} from '../models/index';
import {
    ChannelSelectResponseFromJSON,
    ChannelSelectResponseToJSON,
    ChannelsResponseFromJSON,
    ChannelsResponseToJSON,
    GuildRequestFromJSON,
    GuildRequestToJSON,
    GuildResponseFromJSON,
    GuildResponseToJSON,
    GuildSelectResponseFromJSON,
    GuildSelectResponseToJSON,
    LayerRemoveRequestFromJSON,
    LayerRemoveRequestToJSON,
    LayerVolumeRequestFromJSON,
    LayerVolumeRequestToJSON,
    LoopRequestFromJSON,
    LoopRequestToJSON,
    MusicAddRequestFromJSON,
    MusicAddRequestToJSON,
    MusicAddResponseFromJSON,
    MusicAddResponseToJSON,
    MusicControlRequestFromJSON,
    MusicControlRequestToJSON,
    MusicControlResponseFromJSON,
    MusicControlResponseToJSON,
    MusicStatusResponseFromJSON,
    MusicStatusResponseToJSON,
    SelectChannelRequestFromJSON,
    SelectChannelRequestToJSON,
    SelectGuildRequestFromJSON,
    SelectGuildRequestToJSON,
    ServerStatusModelFromJSON,
    ServerStatusModelToJSON,
    VolumeRequestFromJSON,
    VolumeRequestToJSON,
} from '../models/index';

export interface GetGetChannelsRequest {
    guildId: string | null;
}

export interface GetMusicStatusRequest {
    guildId: string;
}

export interface PostMusicAddRequest {
    musicAddRequest?: MusicAddRequest;
}

export interface PostMusicControlRequest {
    musicControlRequest?: MusicControlRequest;
}

export interface PostMusicLayerCleanRequest {
    guildRequest?: GuildRequest;
}

export interface PostMusicLayerRemoveRequest {
    layerRemoveRequest?: LayerRemoveRequest;
}

export interface PostMusicLayerVolumeRequest {
    layerVolumeRequest?: LayerVolumeRequest;
}

export interface PostMusicLoopRequest {
    loopRequest?: LoopRequest;
}

export interface PostMusicPauseRequest {
    guildRequest?: GuildRequest;
}

export interface PostMusicResumeRequest {
    guildRequest?: GuildRequest;
}

export interface PostMusicSkipRequest {
    guildRequest?: GuildRequest;
}

export interface PostMusicStopRequest {
    guildRequest?: GuildRequest;
}

export interface PostMusicVolumeRequest {
    volumeRequest?: VolumeRequest;
}

export interface PostSelectChannelRequest {
    selectChannelRequest?: SelectChannelRequest;
}

export interface PostSelectGuildRequest {
    selectGuildRequest?: SelectGuildRequest;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Creates request options for getApiServerstatus without sending the request
     */
    async getApiServerstatusRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/serverstatus`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getApiServerstatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServerStatusModel>> {
        const requestOptions = await this.getApiServerstatusRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServerStatusModelFromJSON(jsonValue));
    }

    /**
     */
    async getApiServerstatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServerStatusModel> {
        const response = await this.getApiServerstatusRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGetChannels without sending the request
     */
    async getGetChannelsRequestOpts(requestParameters: GetGetChannelsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['guildId'] == null) {
            throw new runtime.RequiredError(
                'guildId',
                'Required parameter "guildId" was null or undefined when calling getGetChannels().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/guild/{guild_id}/channels`;
        urlPath = urlPath.replace(`{${"guild_id"}}`, encodeURIComponent(String(requestParameters['guildId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getGetChannelsRaw(requestParameters: GetGetChannelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChannelsResponse>> {
        const requestOptions = await this.getGetChannelsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChannelsResponseFromJSON(jsonValue));
    }

    /**
     */
    async getGetChannels(requestParameters: GetGetChannelsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChannelsResponse> {
        const response = await this.getGetChannelsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGetGuilds without sending the request
     */
    async getGetGuildsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/guild`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async getGetGuildsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GuildResponse>>> {
        const requestOptions = await this.getGetGuildsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GuildResponseFromJSON));
    }

    /**
     */
    async getGetGuilds(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GuildResponse>> {
        const response = await this.getGetGuildsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMusicStatus without sending the request
     */
    async getMusicStatusRequestOpts(requestParameters: GetMusicStatusRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['guildId'] == null) {
            throw new runtime.RequiredError(
                'guildId',
                'Required parameter "guildId" was null or undefined when calling getMusicStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/music/{guild_id}/status`;
        urlPath = urlPath.replace(`{${"guild_id"}}`, encodeURIComponent(String(requestParameters['guildId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     *  Query params:     guild_id: The guild ID to get status for.
     * Get music status for a guild.
     */
    async getMusicStatusRaw(requestParameters: GetMusicStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MusicStatusResponse>> {
        const requestOptions = await this.getMusicStatusRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MusicStatusResponseFromJSON(jsonValue));
    }

    /**
     *  Query params:     guild_id: The guild ID to get status for.
     * Get music status for a guild.
     */
    async getMusicStatus(requestParameters: GetMusicStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MusicStatusResponse> {
        const response = await this.getMusicStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postMusicAdd without sending the request
     */
    async postMusicAddRequestOpts(requestParameters: PostMusicAddRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/music/add`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MusicAddRequestToJSON(requestParameters['musicAddRequest']),
        };
    }

    /**
     *  Body:     guild_id: The guild ID.     channel_id: The voice channel ID to connect to.     link: The music URL (YouTube, etc).     type: (Optional) \'queue\' (default) or \'layer\'.
     * Add music to queue via link.
     */
    async postMusicAddRaw(requestParameters: PostMusicAddRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MusicAddResponse>> {
        const requestOptions = await this.postMusicAddRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MusicAddResponseFromJSON(jsonValue));
    }

    /**
     *  Body:     guild_id: The guild ID.     channel_id: The voice channel ID to connect to.     link: The music URL (YouTube, etc).     type: (Optional) \'queue\' (default) or \'layer\'.
     * Add music to queue via link.
     */
    async postMusicAdd(requestParameters: PostMusicAddRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MusicAddResponse> {
        const response = await this.postMusicAddRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postMusicControl without sending the request
     */
    async postMusicControlRequestOpts(requestParameters: PostMusicControlRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/music/control`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MusicControlRequestToJSON(requestParameters['musicControlRequest']),
        };
    }

    /**
     *  .. deprecated::     Use the individual endpoints instead (e.g. POST /api/music/stop).  Body:     guild_id: The guild ID.     action: One of \'stop\', \'skip\', \'pause\', \'resume\', \'loop\',             \'remove_layer\', \'clean_layers\', \'set_volume\', \'set_layer_volume\'.     mode: (Optional) Loop mode for \'loop\' action.     layer_id: (Optional) Layer ID for layer actions.     volume: (Optional) Volume level.
     * Control music playback for a guild.
     */
    async postMusicControlRaw(requestParameters: PostMusicControlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MusicControlResponse>> {
        const requestOptions = await this.postMusicControlRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MusicControlResponseFromJSON(jsonValue));
    }

    /**
     *  .. deprecated::     Use the individual endpoints instead (e.g. POST /api/music/stop).  Body:     guild_id: The guild ID.     action: One of \'stop\', \'skip\', \'pause\', \'resume\', \'loop\',             \'remove_layer\', \'clean_layers\', \'set_volume\', \'set_layer_volume\'.     mode: (Optional) Loop mode for \'loop\' action.     layer_id: (Optional) Layer ID for layer actions.     volume: (Optional) Volume level.
     * Control music playback for a guild.
     */
    async postMusicControl(requestParameters: PostMusicControlRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MusicControlResponse> {
        const response = await this.postMusicControlRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postMusicLayerClean without sending the request
     */
    async postMusicLayerCleanRequestOpts(requestParameters: PostMusicLayerCleanRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/music/layer/clean`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GuildRequestToJSON(requestParameters['guildRequest']),
        };
    }

    /**
     * 
     * Remove all background audio layers.
     */
    async postMusicLayerCleanRaw(requestParameters: PostMusicLayerCleanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MusicControlResponse>> {
        const requestOptions = await this.postMusicLayerCleanRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MusicControlResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Remove all background audio layers.
     */
    async postMusicLayerClean(requestParameters: PostMusicLayerCleanRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MusicControlResponse> {
        const response = await this.postMusicLayerCleanRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postMusicLayerRemove without sending the request
     */
    async postMusicLayerRemoveRequestOpts(requestParameters: PostMusicLayerRemoveRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/music/layer/remove`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LayerRemoveRequestToJSON(requestParameters['layerRemoveRequest']),
        };
    }

    /**
     * 
     * Remove a background audio layer.
     */
    async postMusicLayerRemoveRaw(requestParameters: PostMusicLayerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MusicControlResponse>> {
        const requestOptions = await this.postMusicLayerRemoveRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MusicControlResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Remove a background audio layer.
     */
    async postMusicLayerRemove(requestParameters: PostMusicLayerRemoveRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MusicControlResponse> {
        const response = await this.postMusicLayerRemoveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postMusicLayerVolume without sending the request
     */
    async postMusicLayerVolumeRequestOpts(requestParameters: PostMusicLayerVolumeRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/music/layer/volume`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LayerVolumeRequestToJSON(requestParameters['layerVolumeRequest']),
        };
    }

    /**
     * 
     * Set volume for a specific background audio layer.
     */
    async postMusicLayerVolumeRaw(requestParameters: PostMusicLayerVolumeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MusicControlResponse>> {
        const requestOptions = await this.postMusicLayerVolumeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MusicControlResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Set volume for a specific background audio layer.
     */
    async postMusicLayerVolume(requestParameters: PostMusicLayerVolumeRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MusicControlResponse> {
        const response = await this.postMusicLayerVolumeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postMusicLoop without sending the request
     */
    async postMusicLoopRequestOpts(requestParameters: PostMusicLoopRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/music/loop`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoopRequestToJSON(requestParameters['loopRequest']),
        };
    }

    /**
     * 
     * Set the loop mode (off, track, queue).
     */
    async postMusicLoopRaw(requestParameters: PostMusicLoopRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MusicControlResponse>> {
        const requestOptions = await this.postMusicLoopRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MusicControlResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Set the loop mode (off, track, queue).
     */
    async postMusicLoop(requestParameters: PostMusicLoopRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MusicControlResponse> {
        const response = await this.postMusicLoopRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postMusicPause without sending the request
     */
    async postMusicPauseRequestOpts(requestParameters: PostMusicPauseRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/music/pause`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GuildRequestToJSON(requestParameters['guildRequest']),
        };
    }

    /**
     * 
     * Pause music playback.
     */
    async postMusicPauseRaw(requestParameters: PostMusicPauseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MusicControlResponse>> {
        const requestOptions = await this.postMusicPauseRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MusicControlResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Pause music playback.
     */
    async postMusicPause(requestParameters: PostMusicPauseRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MusicControlResponse> {
        const response = await this.postMusicPauseRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postMusicResume without sending the request
     */
    async postMusicResumeRequestOpts(requestParameters: PostMusicResumeRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/music/resume`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GuildRequestToJSON(requestParameters['guildRequest']),
        };
    }

    /**
     * 
     * Resume music playback.
     */
    async postMusicResumeRaw(requestParameters: PostMusicResumeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MusicControlResponse>> {
        const requestOptions = await this.postMusicResumeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MusicControlResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Resume music playback.
     */
    async postMusicResume(requestParameters: PostMusicResumeRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MusicControlResponse> {
        const response = await this.postMusicResumeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postMusicSkip without sending the request
     */
    async postMusicSkipRequestOpts(requestParameters: PostMusicSkipRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/music/skip`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GuildRequestToJSON(requestParameters['guildRequest']),
        };
    }

    /**
     * 
     * Skip to the next track in the queue.
     */
    async postMusicSkipRaw(requestParameters: PostMusicSkipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MusicControlResponse>> {
        const requestOptions = await this.postMusicSkipRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MusicControlResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Skip to the next track in the queue.
     */
    async postMusicSkip(requestParameters: PostMusicSkipRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MusicControlResponse> {
        const response = await this.postMusicSkipRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postMusicStop without sending the request
     */
    async postMusicStopRequestOpts(requestParameters: PostMusicStopRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/music/stop`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GuildRequestToJSON(requestParameters['guildRequest']),
        };
    }

    /**
     * 
     * Stop music playback for a guild.
     */
    async postMusicStopRaw(requestParameters: PostMusicStopRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MusicControlResponse>> {
        const requestOptions = await this.postMusicStopRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MusicControlResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Stop music playback for a guild.
     */
    async postMusicStop(requestParameters: PostMusicStopRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MusicControlResponse> {
        const response = await this.postMusicStopRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postMusicVolume without sending the request
     */
    async postMusicVolumeRequestOpts(requestParameters: PostMusicVolumeRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/music/volume`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VolumeRequestToJSON(requestParameters['volumeRequest']),
        };
    }

    /**
     * 
     * Set the main playback volume.
     */
    async postMusicVolumeRaw(requestParameters: PostMusicVolumeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MusicControlResponse>> {
        const requestOptions = await this.postMusicVolumeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MusicControlResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Set the main playback volume.
     */
    async postMusicVolume(requestParameters: PostMusicVolumeRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MusicControlResponse> {
        const response = await this.postMusicVolumeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postSelectChannel without sending the request
     */
    async postSelectChannelRequestOpts(requestParameters: PostSelectChannelRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/guild/channel`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SelectChannelRequestToJSON(requestParameters['selectChannelRequest']),
        };
    }

    /**
     */
    async postSelectChannelRaw(requestParameters: PostSelectChannelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChannelSelectResponse>> {
        const requestOptions = await this.postSelectChannelRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChannelSelectResponseFromJSON(jsonValue));
    }

    /**
     */
    async postSelectChannel(requestParameters: PostSelectChannelRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChannelSelectResponse> {
        const response = await this.postSelectChannelRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postSelectGuild without sending the request
     */
    async postSelectGuildRequestOpts(requestParameters: PostSelectGuildRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/guild`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SelectGuildRequestToJSON(requestParameters['selectGuildRequest']),
        };
    }

    /**
     */
    async postSelectGuildRaw(requestParameters: PostSelectGuildRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GuildSelectResponse>> {
        const requestOptions = await this.postSelectGuildRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GuildSelectResponseFromJSON(jsonValue));
    }

    /**
     */
    async postSelectGuild(requestParameters: PostSelectGuildRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GuildSelectResponse> {
        const response = await this.postSelectGuildRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
