"""
This type stub file was generated by pyright.
"""

from google.generativeai import caching, protos, types, version
from google.generativeai.client import configure
from google.generativeai.embedding import embed_content, embed_content_async
from google.generativeai.files import delete_file, get_file, list_files, upload_file
from google.generativeai.generative_models import ChatSession, GenerativeModel
from google.generativeai.models import create_tuned_model, delete_tuned_model, get_base_model, get_model, get_tuned_model, list_models, list_tuned_models, update_tuned_model
from google.generativeai.operations import get_operation, list_operations
from google.generativeai.types import GenerationConfig

__all__ = (
    "caching",
    "protos",
    "types",
    "version",
    "configure",
    "embed_content",
    "embed_content_async",
    "delete_file",
    "get_file",
    "list_files",
    "upload_file",
    "ChatSession",
    "GenerativeModel",
    "create_tuned_model",
    "delete_tuned_model",
    "get_base_model",
    "get_model",
    "get_tuned_model",
    "list_models",
    "list_tuned_models",
    "update_tuned_model",
    "get_operation",
    "list_operations",
    "GenerationConfig"
)

"""Google AI Python SDK

## Setup

```posix-terminal
pip install google-generativeai
```

## GenerativeModel

Use `genai.GenerativeModel` to access the API:

```
import google.generativeai as genai
import os

genai.configure(api_key=os.environ['API_KEY'])

model = genai.GenerativeModel(model_name='gemini-1.5-flash')
response = model.generate_content('Teach me about how an LLM works')

print(response.text)
```

See the [python quickstart](https://ai.google.dev/tutorials/python_quickstart) for more details.
"""
__version__ = ...
