"""
This type stub file was generated by pyright.
"""

def set_doc(doc): # -> Callable[..., Any]:
    """A decorator to set the docstring of a function."""
    ...

def strip_oneof(docstring): # -> LiteralString:
    ...

def prettyprint(cls):
    ...

repr = ...
