"""
This type stub file was generated by pyright.
"""

def flatten_update_paths(updates): # -> dict[Any, Any]:
    """Flattens a nested dictionary into a single level dictionary, with keys representing the original path."""
    ...

