"""
This type stub file was generated by pyright.
"""

from .async_client import CacheServiceAsyncClient
from .client import CacheServiceClient

__all__ = ("CacheServiceClient", "CacheServiceAsyncClient")
