"""
This type stub file was generated by pyright.
"""

from typing import ClassVar as _ClassVar
from google.protobuf import descriptor as _descriptor

DESCRIPTOR: _descriptor.FileDescriptor
HTTP_FIELD_NUMBER: _ClassVar[int]
http: _descriptor.FieldDescriptor
