"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Optional
from google.api_core import gapic_v1
from .base import FileServiceTransport

class _BaseFileServiceRestTransport(FileServiceTransport):
    """Base REST backend transport for FileService.

    Note: This class is not meant to be used directly. Use its sync and
    async sub-classes instead.

    This class defines the same methods as the primary client, so the
    primary client can load the underlying transport implementation
    and call it.

    It sends JSON representations of protocol buffers over HTTP/1.1
    """
    def __init__(self, *, host: str = ..., credentials: Optional[Any] = ..., client_info: gapic_v1.client_info.ClientInfo = ..., always_use_jwt_access: Optional[bool] = ..., url_scheme: str = ..., api_audience: Optional[str] = ...) -> None:
        """Instantiate the transport.
        Args:
            host (Optional[str]):
                 The hostname to connect to (default: 'generativelanguage.googleapis.com').
            credentials (Optional[Any]): The
                authorization credentials to attach to requests. These
                credentials identify the application to the service; if none
                are specified, the client will attempt to ascertain the
                credentials from the environment.
            client_info (google.api_core.gapic_v1.client_info.ClientInfo):
                The client info used to send a user-agent string along with
                API requests. If ``None``, then default info will be used.
                Generally, you only need to set this if you are developing
                your own client library.
            always_use_jwt_access (Optional[bool]): Whether self signed JWT should
                be used for service account credentials.
            url_scheme: the protocol scheme for the API endpoint.  Normally
                "https", but for testing or local servers,
                "http" can be specified.
        """
        ...
    
    class _BaseCreateFile:
        def __hash__(self) -> int:
            ...
        
    
    
    class _BaseDeleteFile:
        def __hash__(self) -> int:
            ...
        
        __REQUIRED_FIELDS_DEFAULT_VALUES: Dict[str, Any] = ...
    
    
    class _BaseGetFile:
        def __hash__(self) -> int:
            ...
        
        __REQUIRED_FIELDS_DEFAULT_VALUES: Dict[str, Any] = ...
    
    
    class _BaseListFiles:
        def __hash__(self) -> int:
            ...
        
    
    
    class _BaseGetOperation:
        def __hash__(self) -> int:
            ...
        
    
    
    class _BaseListOperations:
        def __hash__(self) -> int:
            ...
        
    
    


__all__ = ("_BaseFileServiceRestTransport", )
