"""
This type stub file was generated by pyright.
"""

"""Notebook extensions for Generative AI."""
def load_ipython_extension(ipython): # -> None:
    """Register the Colab Magic extension to support %load_ext."""
    ...

